import type {
  Industry,
  UserRole,
  ContactType,
  ContactStatus,
  OpportunityType,
  OpportunityStatus,
  EstimateStatus,
  CampaignType,
  CampaignStatus,
  ChannelType,
  BookingSourceType,
  AttributionMethod,
  IntegrationProvider,
  IntegrationStatus,
} from "@prisma/client";
import type {
  Alert,
  ActivityItem,
  WorkflowPerformanceData,
  RecoveryTrendData,
  ReactivationSegment,
  IntegrationCard,
} from "@/types";

// ─── HELPERS ───────────────────────────────────────────

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

function ago(ms: number): Date {
  return new Date(Date.now() - ms);
}

function futureDate(ms: number): Date {
  return new Date(Date.now() + ms);
}

function dateStr(daysAgo: number): string {
  const d = ago(daysAgo * DAY);
  return d.toISOString().slice(0, 10);
}

// ─── BUSINESS ──────────────────────────────────────────

export interface DemoBusiness {
  id: string;
  name: string;
  industry: Industry;
  timezone: string;
  staleEstimateDays: number;
  attributionWindowDays: number;
  highValueThreshold: number;
  missedCallSuppressionMinutes: number;
  phone: string;
  email: string;
  website: string;
  logoUrl: string | null;
  address: string;
  city: string;
  state: string;
  zip: string;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_BUSINESS: DemoBusiness = {
  id: "biz_1",
  name: "North Shore Heating & Plumbing",
  industry: "multi_trade" as Industry,
  timezone: "America/Detroit",
  staleEstimateDays: 7,
  attributionWindowDays: 14,
  highValueThreshold: 2500,
  missedCallSuppressionMinutes: 240,
  phone: "+12485551000",
  email: "info@northshoreheating.com",
  website: "https://northshoreheating.com",
  logoUrl: null,
  address: "4820 Woodward Ave",
  city: "Royal Oak",
  state: "MI",
  zip: "48073",
  createdAt: ago(180 * DAY),
  updatedAt: ago(1 * DAY),
};

// ─── USERS ─────────────────────────────────────────────

export interface DemoUser {
  id: string;
  businessId: string;
  email: string;
  name: string;
  role: UserRole;
  avatarUrl: string | null;
  phone: string;
  isActive: boolean;
  lastLoginAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_USERS: DemoUser[] = [
  {
    id: "usr_1",
    businessId: "biz_1",
    email: "mike@northshoreheating.com",
    name: "Mike Reynolds",
    role: "owner" as UserRole,
    avatarUrl: null,
    phone: "+12485551001",
    isActive: true,
    lastLoginAt: ago(0.5 * HOUR),
    createdAt: ago(180 * DAY),
    updatedAt: ago(0.5 * HOUR),
  },
  {
    id: "usr_2",
    businessId: "biz_1",
    email: "sarah@northshoreheating.com",
    name: "Sarah Chen",
    role: "manager" as UserRole,
    avatarUrl: null,
    phone: "+12485551002",
    isActive: true,
    lastLoginAt: ago(2 * HOUR),
    createdAt: ago(160 * DAY),
    updatedAt: ago(2 * HOUR),
  },
  {
    id: "usr_3",
    businessId: "biz_1",
    email: "jake@northshoreheating.com",
    name: "Jake Morrison",
    role: "csr" as UserRole,
    avatarUrl: null,
    phone: "+12485551003",
    isActive: true,
    lastLoginAt: ago(1 * HOUR),
    createdAt: ago(120 * DAY),
    updatedAt: ago(1 * HOUR),
  },
];

// ─── CONTACTS ──────────────────────────────────────────

export interface DemoContact {
  id: string;
  businessId: string;
  firstName: string;
  lastName: string;
  email: string | null;
  phone: string;
  type: ContactType;
  status: ContactStatus;
  address: string;
  city: string;
  state: string;
  zip: string;
  tags: string[];
  source: string;
  lastServiceAt: Date | null;
  lifetime_value: number;
  notes: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_CONTACTS: DemoContact[] = [
  {
    id: "cnt_1",
    businessId: "biz_1",
    firstName: "John",
    lastName: "Kowalski",
    email: "john.kowalski@gmail.com",
    phone: "+12485559101",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "312 Maple St",
    city: "Royal Oak",
    state: "MI",
    zip: "48067",
    tags: ["furnace", "maintenance-plan"],
    source: "referral",
    lastServiceAt: ago(45 * DAY),
    lifetime_value: 4200,
    notes: "Preferred customer, has maintenance plan",
    createdAt: ago(400 * DAY),
    updatedAt: ago(45 * DAY),
  },
  {
    id: "cnt_2",
    businessId: "biz_1",
    firstName: "Maria",
    lastName: "Gonzalez",
    email: "maria.g@outlook.com",
    phone: "+13135559202",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "8901 Livernois Ave",
    city: "Detroit",
    state: "MI",
    zip: "48204",
    tags: ["plumbing", "water-heater"],
    source: "website",
    lastServiceAt: ago(20 * DAY),
    lifetime_value: 3100,
    notes: null,
    createdAt: ago(300 * DAY),
    updatedAt: ago(20 * DAY),
  },
  {
    id: "cnt_3",
    businessId: "biz_1",
    firstName: "Robert",
    lastName: "Thompson",
    email: "rthompson@yahoo.com",
    phone: "+15865559303",
    type: "former_customer" as ContactType,
    status: "dormant" as ContactStatus,
    address: "1445 Gratiot Ave",
    city: "Clinton Township",
    state: "MI",
    zip: "48035",
    tags: ["hvac", "duct-cleaning"],
    source: "google",
    lastServiceAt: ago(380 * DAY),
    lifetime_value: 1800,
    notes: "Had furnace installed 2022",
    createdAt: ago(700 * DAY),
    updatedAt: ago(380 * DAY),
  },
  {
    id: "cnt_4",
    businessId: "biz_1",
    firstName: "Lisa",
    lastName: "Patel",
    email: "lisa.patel@gmail.com",
    phone: "+12485559404",
    type: "lead" as ContactType,
    status: "active" as ContactStatus,
    address: "2200 Cole St",
    city: "Birmingham",
    state: "MI",
    zip: "48009",
    tags: ["ac-install"],
    source: "missed_call",
    lastServiceAt: null,
    lifetime_value: 0,
    notes: null,
    createdAt: ago(3 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "cnt_5",
    businessId: "biz_1",
    firstName: "James",
    lastName: "O'Brien",
    email: "jobrien@comcast.net",
    phone: "+12485559505",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "555 Woodward Heights",
    city: "Ferndale",
    state: "MI",
    zip: "48220",
    tags: ["furnace", "ac", "maintenance-plan"],
    source: "referral",
    lastServiceAt: ago(90 * DAY),
    lifetime_value: 8700,
    notes: "Long-time customer, two systems",
    createdAt: ago(900 * DAY),
    updatedAt: ago(90 * DAY),
  },
  {
    id: "cnt_6",
    businessId: "biz_1",
    firstName: "Angela",
    lastName: "Williams",
    email: "awilliams@gmail.com",
    phone: "+13135559606",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "780 Lakeshore Dr",
    city: "Grosse Pointe",
    state: "MI",
    zip: "48230",
    tags: ["plumbing", "bathroom-remodel"],
    source: "website",
    lastServiceAt: ago(15 * DAY),
    lifetime_value: 6200,
    notes: null,
    createdAt: ago(500 * DAY),
    updatedAt: ago(15 * DAY),
  },
  {
    id: "cnt_7",
    businessId: "biz_1",
    firstName: "David",
    lastName: "Kim",
    email: "dkim@gmail.com",
    phone: "+15865559707",
    type: "lead" as ContactType,
    status: "active" as ContactStatus,
    address: "3300 Rochester Rd",
    city: "Troy",
    state: "MI",
    zip: "48083",
    tags: ["furnace-repair"],
    source: "google",
    lastServiceAt: null,
    lifetime_value: 0,
    notes: "Called about furnace not heating",
    createdAt: ago(1 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "cnt_8",
    businessId: "biz_1",
    firstName: "Patricia",
    lastName: "Murphy",
    email: "pmurphy@att.net",
    phone: "+12485559808",
    type: "former_customer" as ContactType,
    status: "dormant" as ContactStatus,
    address: "920 Crooks Rd",
    city: "Clawson",
    state: "MI",
    zip: "48017",
    tags: ["furnace", "ac"],
    source: "referral",
    lastServiceAt: ago(420 * DAY),
    lifetime_value: 5500,
    notes: "Moved to new home, may need new install",
    createdAt: ago(800 * DAY),
    updatedAt: ago(420 * DAY),
  },
  {
    id: "cnt_9",
    businessId: "biz_1",
    firstName: "Michael",
    lastName: "Russo",
    email: "mrusso@hotmail.com",
    phone: "+13135559909",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "6145 Michigan Ave",
    city: "Dearborn",
    state: "MI",
    zip: "48126",
    tags: ["plumbing", "drain-cleaning"],
    source: "google",
    lastServiceAt: ago(60 * DAY),
    lifetime_value: 2400,
    notes: null,
    createdAt: ago(350 * DAY),
    updatedAt: ago(60 * DAY),
  },
  {
    id: "cnt_10",
    businessId: "biz_1",
    firstName: "Jennifer",
    lastName: "Chang",
    email: "jchang@gmail.com",
    phone: "+12485550010",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "1100 S Adams Rd",
    city: "Birmingham",
    state: "MI",
    zip: "48009",
    tags: ["ac", "maintenance-plan"],
    source: "website",
    lastServiceAt: ago(30 * DAY),
    lifetime_value: 3600,
    notes: null,
    createdAt: ago(450 * DAY),
    updatedAt: ago(30 * DAY),
  },
  {
    id: "cnt_11",
    businessId: "biz_1",
    firstName: "William",
    lastName: "Foster",
    email: null,
    phone: "+15865550011",
    type: "lead" as ContactType,
    status: "active" as ContactStatus,
    address: "2750 Van Dyke Ave",
    city: "Warren",
    state: "MI",
    zip: "48093",
    tags: ["water-heater"],
    source: "missed_call",
    lastServiceAt: null,
    lifetime_value: 0,
    notes: null,
    createdAt: ago(2 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "cnt_12",
    businessId: "biz_1",
    firstName: "Susan",
    lastName: "Novak",
    email: "snovak@gmail.com",
    phone: "+12485550012",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "430 W Lincoln Ave",
    city: "Royal Oak",
    state: "MI",
    zip: "48067",
    tags: ["furnace", "humidifier"],
    source: "referral",
    lastServiceAt: ago(100 * DAY),
    lifetime_value: 4800,
    notes: "Referred by John Kowalski",
    createdAt: ago(600 * DAY),
    updatedAt: ago(100 * DAY),
  },
  {
    id: "cnt_13",
    businessId: "biz_1",
    firstName: "Daniel",
    lastName: "Abrams",
    email: "dabrams@outlook.com",
    phone: "+13135550013",
    type: "former_customer" as ContactType,
    status: "dormant" as ContactStatus,
    address: "5580 Cass Ave",
    city: "Detroit",
    state: "MI",
    zip: "48202",
    tags: ["hvac"],
    source: "google",
    lastServiceAt: ago(500 * DAY),
    lifetime_value: 2200,
    notes: null,
    createdAt: ago(750 * DAY),
    updatedAt: ago(500 * DAY),
  },
  {
    id: "cnt_14",
    businessId: "biz_1",
    firstName: "Karen",
    lastName: "Whitfield",
    email: "kwhitfield@yahoo.com",
    phone: "+12485550014",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "1885 Catalpa Dr",
    city: "Berkley",
    state: "MI",
    zip: "48072",
    tags: ["furnace", "ac", "duct-cleaning"],
    source: "website",
    lastServiceAt: ago(70 * DAY),
    lifetime_value: 7100,
    notes: null,
    createdAt: ago(650 * DAY),
    updatedAt: ago(70 * DAY),
  },
  {
    id: "cnt_15",
    businessId: "biz_1",
    firstName: "Steven",
    lastName: "Bakshi",
    email: "sbakshi@gmail.com",
    phone: "+15865550015",
    type: "lead" as ContactType,
    status: "active" as ContactStatus,
    address: "9200 Hall Rd",
    city: "Macomb",
    state: "MI",
    zip: "48044",
    tags: ["ac-install"],
    source: "google",
    lastServiceAt: null,
    lifetime_value: 0,
    notes: "Requested AC quote",
    createdAt: ago(5 * DAY),
    updatedAt: ago(5 * DAY),
  },
  {
    id: "cnt_16",
    businessId: "biz_1",
    firstName: "Nancy",
    lastName: "Kowalczyk",
    email: "nkowalczyk@comcast.net",
    phone: "+12485550016",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "775 Torquay Ave",
    city: "Royal Oak",
    state: "MI",
    zip: "48073",
    tags: ["plumbing", "sump-pump"],
    source: "referral",
    lastServiceAt: ago(35 * DAY),
    lifetime_value: 3200,
    notes: null,
    createdAt: ago(400 * DAY),
    updatedAt: ago(35 * DAY),
  },
  {
    id: "cnt_17",
    businessId: "biz_1",
    firstName: "Brian",
    lastName: "Henderson",
    email: "bhenderson@gmail.com",
    phone: "+13135550017",
    type: "former_customer" as ContactType,
    status: "dormant" as ContactStatus,
    address: "2210 W Grand Blvd",
    city: "Detroit",
    state: "MI",
    zip: "48208",
    tags: ["furnace"],
    source: "google",
    lastServiceAt: ago(450 * DAY),
    lifetime_value: 1600,
    notes: null,
    createdAt: ago(700 * DAY),
    updatedAt: ago(450 * DAY),
  },
  {
    id: "cnt_18",
    businessId: "biz_1",
    firstName: "Emily",
    lastName: "Larson",
    email: "elarson@gmail.com",
    phone: "+12485550018",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "340 Coolidge Hwy",
    city: "Pleasant Ridge",
    state: "MI",
    zip: "48069",
    tags: ["ac", "furnace"],
    source: "website",
    lastServiceAt: ago(120 * DAY),
    lifetime_value: 5900,
    notes: "Full system installed 2023",
    createdAt: ago(500 * DAY),
    updatedAt: ago(120 * DAY),
  },
  {
    id: "cnt_19",
    businessId: "biz_1",
    firstName: "Thomas",
    lastName: "Jankowski",
    email: null,
    phone: "+15865550019",
    type: "lead" as ContactType,
    status: "active" as ContactStatus,
    address: "4400 Garfield Rd",
    city: "Clinton Township",
    state: "MI",
    zip: "48038",
    tags: ["plumbing"],
    source: "missed_call",
    lastServiceAt: null,
    lifetime_value: 0,
    notes: null,
    createdAt: ago(0.5 * DAY),
    updatedAt: ago(0.5 * DAY),
  },
  {
    id: "cnt_20",
    businessId: "biz_1",
    firstName: "Rachel",
    lastName: "Steinberg",
    email: "rsteinberg@gmail.com",
    phone: "+12485550020",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "1560 Southfield Rd",
    city: "Birmingham",
    state: "MI",
    zip: "48009",
    tags: ["maintenance-plan", "furnace", "ac"],
    source: "referral",
    lastServiceAt: ago(25 * DAY),
    lifetime_value: 9200,
    notes: "VIP customer",
    createdAt: ago(850 * DAY),
    updatedAt: ago(25 * DAY),
  },
  {
    id: "cnt_21",
    businessId: "biz_1",
    firstName: "Mark",
    lastName: "Alvarez",
    email: "malvarez@outlook.com",
    phone: "+13135550021",
    type: "customer" as ContactType,
    status: "active" as ContactStatus,
    address: "3750 Fort St",
    city: "Lincoln Park",
    state: "MI",
    zip: "48146",
    tags: ["furnace-repair"],
    source: "google",
    lastServiceAt: ago(150 * DAY),
    lifetime_value: 1900,
    notes: null,
    createdAt: ago(350 * DAY),
    updatedAt: ago(150 * DAY),
  },
  {
    id: "cnt_22",
    businessId: "biz_1",
    firstName: "Diane",
    lastName: "Crawford",
    email: "dcrawford@yahoo.com",
    phone: "+12485550022",
    type: "former_customer" as ContactType,
    status: "dormant" as ContactStatus,
    address: "880 E Fourth St",
    city: "Royal Oak",
    state: "MI",
    zip: "48067",
    tags: ["plumbing", "water-heater"],
    source: "website",
    lastServiceAt: ago(365 * DAY),
    lifetime_value: 3400,
    notes: "Water heater may be due for replacement",
    createdAt: ago(600 * DAY),
    updatedAt: ago(365 * DAY),
  },
];

// ─── OPPORTUNITIES ─────────────────────────────────────

export interface DemoOpportunity {
  id: string;
  businessId: string;
  contactId: string;
  assignedToId: string | null;
  type: OpportunityType;
  status: OpportunityStatus;
  title: string;
  description: string | null;
  estimatedValue: number | null;
  actualValue: number | null;
  serviceType: string | null;
  priority: number;
  source: string | null;
  attribution: AttributionMethod;
  resolvedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_OPPORTUNITIES: DemoOpportunity[] = [
  {
    id: "opp_1",
    businessId: "biz_1",
    contactId: "cnt_7",
    assignedToId: "usr_3",
    type: "missed_call" as OpportunityType,
    status: "new" as OpportunityStatus,
    title: "Missed call - furnace not heating",
    description: "Customer called about furnace issues, after-hours call missed",
    estimatedValue: 450,
    actualValue: null,
    serviceType: "Furnace Repair",
    priority: 2,
    source: "phone",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(1 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "opp_2",
    businessId: "biz_1",
    contactId: "cnt_4",
    assignedToId: "usr_2",
    type: "missed_call" as OpportunityType,
    status: "attempted" as OpportunityStatus,
    title: "Missed call - AC installation inquiry",
    description: "Potential new AC install, SMS follow-up sent",
    estimatedValue: 5500,
    actualValue: null,
    serviceType: "AC Installation",
    priority: 3,
    source: "phone",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(3 * DAY),
    updatedAt: ago(2.5 * DAY),
  },
  {
    id: "opp_3",
    businessId: "biz_1",
    contactId: "cnt_11",
    assignedToId: "usr_3",
    type: "missed_call" as OpportunityType,
    status: "responded" as OpportunityStatus,
    title: "Missed call - water heater leaking",
    description: "Emergency water heater issue, customer responded to follow-up SMS",
    estimatedValue: 1800,
    actualValue: null,
    serviceType: "Water Heater Replacement",
    priority: 3,
    source: "phone",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(2 * DAY),
    updatedAt: ago(1.5 * DAY),
  },
  {
    id: "opp_4",
    businessId: "biz_1",
    contactId: "cnt_19",
    assignedToId: null,
    type: "missed_call" as OpportunityType,
    status: "new" as OpportunityStatus,
    title: "Missed call - plumbing emergency",
    description: "After-hours call, no voicemail left",
    estimatedValue: 350,
    actualValue: null,
    serviceType: "Plumbing Repair",
    priority: 1,
    source: "phone",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(0.5 * DAY),
    updatedAt: ago(0.5 * DAY),
  },
  {
    id: "opp_5",
    businessId: "biz_1",
    contactId: "cnt_15",
    assignedToId: "usr_2",
    type: "estimate_rescue" as OpportunityType,
    status: "attempted" as OpportunityStatus,
    title: "Stale estimate - AC replacement",
    description: "Estimate sent 12 days ago, no response. Follow-up SMS sent.",
    estimatedValue: 6200,
    actualValue: null,
    serviceType: "AC Installation",
    priority: 3,
    source: "estimate",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(5 * DAY),
    updatedAt: ago(4 * DAY),
  },
  {
    id: "opp_6",
    businessId: "biz_1",
    contactId: "cnt_1",
    assignedToId: "usr_1",
    type: "estimate_rescue" as OpportunityType,
    status: "booked" as OpportunityStatus,
    title: "Stale estimate - furnace tune-up",
    description: "Customer re-engaged after follow-up, booked service",
    estimatedValue: 250,
    actualValue: 250,
    serviceType: "Furnace Maintenance",
    priority: 1,
    source: "estimate",
    attribution: "direct" as AttributionMethod,
    resolvedAt: ago(1 * DAY),
    createdAt: ago(10 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "opp_7",
    businessId: "biz_1",
    contactId: "cnt_6",
    assignedToId: "usr_2",
    type: "estimate_rescue" as OpportunityType,
    status: "qualified" as OpportunityStatus,
    title: "Stale estimate - bathroom remodel plumbing",
    description: "Customer interested, requested updated pricing",
    estimatedValue: 8500,
    actualValue: null,
    serviceType: "Plumbing Remodel",
    priority: 3,
    source: "estimate",
    attribution: "direct" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(8 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "opp_8",
    businessId: "biz_1",
    contactId: "cnt_10",
    assignedToId: "usr_3",
    type: "estimate_rescue" as OpportunityType,
    status: "lost" as OpportunityStatus,
    title: "Stale estimate - AC repair",
    description: "Customer went with another company",
    estimatedValue: 1200,
    actualValue: null,
    serviceType: "AC Repair",
    priority: 1,
    source: "estimate",
    attribution: "direct" as AttributionMethod,
    resolvedAt: ago(2 * DAY),
    createdAt: ago(14 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "opp_9",
    businessId: "biz_1",
    contactId: "cnt_3",
    assignedToId: "usr_2",
    type: "reactivation" as OpportunityType,
    status: "attempted" as OpportunityStatus,
    title: "Reactivation - annual maintenance",
    description: "No service in 12+ months, reactivation SMS sent",
    estimatedValue: 200,
    actualValue: null,
    serviceType: "Annual Maintenance",
    priority: 1,
    source: "campaign",
    attribution: "influenced" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(7 * DAY),
    updatedAt: ago(6 * DAY),
  },
  {
    id: "opp_10",
    businessId: "biz_1",
    contactId: "cnt_8",
    assignedToId: "usr_1",
    type: "reactivation" as OpportunityType,
    status: "responded" as OpportunityStatus,
    title: "Reactivation - new home HVAC setup",
    description: "Former customer moved, interested in full system install",
    estimatedValue: 7500,
    actualValue: null,
    serviceType: "HVAC Installation",
    priority: 3,
    source: "campaign",
    attribution: "influenced" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(6 * DAY),
    updatedAt: ago(4 * DAY),
  },
  {
    id: "opp_11",
    businessId: "biz_1",
    contactId: "cnt_13",
    assignedToId: "usr_3",
    type: "reactivation" as OpportunityType,
    status: "booked" as OpportunityStatus,
    title: "Reactivation - furnace inspection",
    description: "Dormant customer re-engaged, booked inspection",
    estimatedValue: 150,
    actualValue: 150,
    serviceType: "Furnace Inspection",
    priority: 1,
    source: "campaign",
    attribution: "influenced" as AttributionMethod,
    resolvedAt: ago(2 * DAY),
    createdAt: ago(9 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "opp_12",
    businessId: "biz_1",
    contactId: "cnt_17",
    assignedToId: null,
    type: "reactivation" as OpportunityType,
    status: "new" as OpportunityStatus,
    title: "Reactivation - heating system checkup",
    description: "No service in 15+ months, eligible for reactivation",
    estimatedValue: 200,
    actualValue: null,
    serviceType: "Heating Maintenance",
    priority: 1,
    source: "campaign",
    attribution: "influenced" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(4 * DAY),
    updatedAt: ago(4 * DAY),
  },
  {
    id: "opp_13",
    businessId: "biz_1",
    contactId: "cnt_22",
    assignedToId: "usr_2",
    type: "reactivation" as OpportunityType,
    status: "qualified" as OpportunityStatus,
    title: "Reactivation - water heater replacement",
    description: "Water heater is 10+ years old, customer interested in replacement",
    estimatedValue: 2800,
    actualValue: null,
    serviceType: "Water Heater Replacement",
    priority: 2,
    source: "campaign",
    attribution: "influenced" as AttributionMethod,
    resolvedAt: null,
    createdAt: ago(5 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "opp_14",
    businessId: "biz_1",
    contactId: "cnt_2",
    assignedToId: "usr_1",
    type: "missed_call" as OpportunityType,
    status: "booked" as OpportunityStatus,
    title: "Missed call - drain clog",
    description: "Follow-up SMS led to booking for drain cleaning",
    estimatedValue: 300,
    actualValue: 350,
    serviceType: "Drain Cleaning",
    priority: 2,
    source: "phone",
    attribution: "direct" as AttributionMethod,
    resolvedAt: ago(1 * DAY),
    createdAt: ago(4 * DAY),
    updatedAt: ago(1 * DAY),
  },
];

// ─── CALL EVENTS ───────────────────────────────────────

export interface DemoCallEvent {
  id: string;
  businessId: string;
  contactId: string | null;
  opportunityId: string | null;
  callerNumber: string;
  calledNumber: string;
  direction: string;
  status: string;
  duration: number | null;
  isAfterHours: boolean;
  callStartedAt: Date;
  callEndedAt: Date | null;
  recordingUrl: string | null;
  transcription: string | null;
  intakeSummary: string | null;
  createdAt: Date;
}

export const DEMO_CALL_EVENTS: DemoCallEvent[] = [
  {
    id: "call_1",
    businessId: "biz_1",
    contactId: "cnt_7",
    opportunityId: "opp_1",
    callerNumber: "+15865559707",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: true,
    callStartedAt: ago(1 * DAY + 2 * HOUR),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: "Furnace not heating - after hours missed call",
    createdAt: ago(1 * DAY + 2 * HOUR),
  },
  {
    id: "call_2",
    businessId: "biz_1",
    contactId: "cnt_4",
    opportunityId: "opp_2",
    callerNumber: "+12485559404",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: false,
    callStartedAt: ago(3 * DAY + 4 * HOUR),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: "AC installation inquiry - call missed during lunch",
    createdAt: ago(3 * DAY + 4 * HOUR),
  },
  {
    id: "call_3",
    businessId: "biz_1",
    contactId: "cnt_11",
    opportunityId: "opp_3",
    callerNumber: "+15865550011",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: true,
    callStartedAt: ago(2 * DAY + 6 * HOUR),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: "Water heater leaking - emergency call after hours",
    createdAt: ago(2 * DAY + 6 * HOUR),
  },
  {
    id: "call_4",
    businessId: "biz_1",
    contactId: "cnt_19",
    opportunityId: "opp_4",
    callerNumber: "+15865550019",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: true,
    callStartedAt: ago(0.5 * DAY),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: null,
    createdAt: ago(0.5 * DAY),
  },
  {
    id: "call_5",
    businessId: "biz_1",
    contactId: "cnt_2",
    opportunityId: "opp_14",
    callerNumber: "+13135559202",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: false,
    callStartedAt: ago(4 * DAY + 3 * HOUR),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: "Drain clog, needs service today if possible",
    createdAt: ago(4 * DAY + 3 * HOUR),
  },
  {
    id: "call_6",
    businessId: "biz_1",
    contactId: "cnt_1",
    opportunityId: null,
    callerNumber: "+12485559101",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "answered",
    duration: 185,
    isAfterHours: false,
    callStartedAt: ago(5 * DAY + 1 * HOUR),
    callEndedAt: ago(5 * DAY + 1 * HOUR - 185000),
    recordingUrl: null,
    transcription: "Customer called about scheduling annual furnace tune-up. Booked for next week.",
    intakeSummary: "Annual maintenance scheduling",
    createdAt: ago(5 * DAY + 1 * HOUR),
  },
  {
    id: "call_7",
    businessId: "biz_1",
    contactId: "cnt_6",
    opportunityId: null,
    callerNumber: "+13135559606",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "answered",
    duration: 420,
    isAfterHours: false,
    callStartedAt: ago(3 * DAY + 5 * HOUR),
    callEndedAt: ago(3 * DAY + 5 * HOUR - 420000),
    recordingUrl: null,
    transcription: "Discussion about bathroom remodel plumbing scope and updated pricing.",
    intakeSummary: "Bathroom remodel follow-up discussion",
    createdAt: ago(3 * DAY + 5 * HOUR),
  },
  {
    id: "call_8",
    businessId: "biz_1",
    contactId: "cnt_20",
    opportunityId: null,
    callerNumber: "+12485550020",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "answered",
    duration: 95,
    isAfterHours: false,
    callStartedAt: ago(2 * DAY + 3 * HOUR),
    callEndedAt: ago(2 * DAY + 3 * HOUR - 95000),
    recordingUrl: null,
    transcription: null,
    intakeSummary: "VIP customer checking on maintenance plan renewal",
    createdAt: ago(2 * DAY + 3 * HOUR),
  },
  {
    id: "call_9",
    businessId: "biz_1",
    contactId: "cnt_9",
    opportunityId: null,
    callerNumber: "+13135559909",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "answered",
    duration: 210,
    isAfterHours: false,
    callStartedAt: ago(6 * DAY + 2 * HOUR),
    callEndedAt: ago(6 * DAY + 2 * HOUR - 210000),
    recordingUrl: null,
    transcription: "Customer inquiring about drain cleaning service options and pricing.",
    intakeSummary: "Drain cleaning inquiry",
    createdAt: ago(6 * DAY + 2 * HOUR),
  },
  {
    id: "call_10",
    businessId: "biz_1",
    contactId: null,
    opportunityId: null,
    callerNumber: "+12485550099",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "missed",
    duration: null,
    isAfterHours: false,
    callStartedAt: ago(0.25 * DAY),
    callEndedAt: null,
    recordingUrl: null,
    transcription: null,
    intakeSummary: null,
    createdAt: ago(0.25 * DAY),
  },
  {
    id: "call_11",
    businessId: "biz_1",
    contactId: "cnt_14",
    opportunityId: null,
    callerNumber: "+12485550014",
    calledNumber: "+12485551000",
    direction: "inbound",
    status: "answered",
    duration: 310,
    isAfterHours: false,
    callStartedAt: ago(1 * DAY + 4 * HOUR),
    callEndedAt: ago(1 * DAY + 4 * HOUR - 310000),
    recordingUrl: null,
    transcription: "Customer scheduling duct cleaning and discussing HVAC filter options.",
    intakeSummary: "Duct cleaning scheduling and filter inquiry",
    createdAt: ago(1 * DAY + 4 * HOUR),
  },
];

// ─── ESTIMATES ─────────────────────────────────────────

export interface DemoEstimate {
  id: string;
  businessId: string;
  contactId: string;
  opportunityId: string | null;
  externalId: string;
  title: string;
  amount: number;
  status: EstimateStatus;
  serviceType: string;
  sentAt: Date;
  followUpAt: Date | null;
  expiresAt: Date | null;
  staleSince: Date | null;
  respondedAt: Date | null;
  bookedAt: Date | null;
  lostAt: Date | null;
  lostReason: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_ESTIMATES: DemoEstimate[] = [
  {
    id: "est_1",
    businessId: "biz_1",
    contactId: "cnt_15",
    opportunityId: "opp_5",
    externalId: "EST-1042",
    title: "Central AC Replacement - 3 Ton",
    amount: 6200,
    status: "stale" as EstimateStatus,
    serviceType: "AC Installation",
    sentAt: ago(14 * DAY),
    followUpAt: ago(4 * DAY),
    expiresAt: futureDate(16 * DAY),
    staleSince: ago(7 * DAY),
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(14 * DAY),
    updatedAt: ago(4 * DAY),
  },
  {
    id: "est_2",
    businessId: "biz_1",
    contactId: "cnt_1",
    opportunityId: "opp_6",
    externalId: "EST-1038",
    title: "Furnace Annual Tune-Up",
    amount: 250,
    status: "booked" as EstimateStatus,
    serviceType: "Furnace Maintenance",
    sentAt: ago(12 * DAY),
    followUpAt: ago(5 * DAY),
    expiresAt: null,
    staleSince: ago(5 * DAY),
    respondedAt: ago(3 * DAY),
    bookedAt: ago(1 * DAY),
    lostAt: null,
    lostReason: null,
    createdAt: ago(12 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "est_3",
    businessId: "biz_1",
    contactId: "cnt_6",
    opportunityId: "opp_7",
    externalId: "EST-1035",
    title: "Bathroom Remodel Plumbing Package",
    amount: 8500,
    status: "responded" as EstimateStatus,
    serviceType: "Plumbing Remodel",
    sentAt: ago(18 * DAY),
    followUpAt: ago(8 * DAY),
    expiresAt: futureDate(12 * DAY),
    staleSince: ago(11 * DAY),
    respondedAt: ago(3 * DAY),
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(18 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "est_4",
    businessId: "biz_1",
    contactId: "cnt_10",
    opportunityId: "opp_8",
    externalId: "EST-1030",
    title: "AC Compressor Repair",
    amount: 1200,
    status: "lost" as EstimateStatus,
    serviceType: "AC Repair",
    sentAt: ago(21 * DAY),
    followUpAt: ago(14 * DAY),
    expiresAt: ago(1 * DAY),
    staleSince: ago(14 * DAY),
    respondedAt: null,
    bookedAt: null,
    lostAt: ago(2 * DAY),
    lostReason: "Went with competitor - lower price",
    createdAt: ago(21 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "est_5",
    businessId: "biz_1",
    contactId: "cnt_9",
    opportunityId: null,
    externalId: "EST-1045",
    title: "Main Line Drain Cleaning",
    amount: 450,
    status: "open" as EstimateStatus,
    serviceType: "Drain Cleaning",
    sentAt: ago(3 * DAY),
    followUpAt: null,
    expiresAt: futureDate(27 * DAY),
    staleSince: null,
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(3 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "est_6",
    businessId: "biz_1",
    contactId: "cnt_14",
    opportunityId: null,
    externalId: "EST-1044",
    title: "Whole-Home Duct Cleaning",
    amount: 550,
    status: "open" as EstimateStatus,
    serviceType: "Duct Cleaning",
    sentAt: ago(4 * DAY),
    followUpAt: null,
    expiresAt: futureDate(26 * DAY),
    staleSince: null,
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(4 * DAY),
    updatedAt: ago(4 * DAY),
  },
  {
    id: "est_7",
    businessId: "biz_1",
    contactId: "cnt_22",
    opportunityId: "opp_13",
    externalId: "EST-1025",
    title: "50-Gallon Water Heater Installation",
    amount: 2800,
    status: "stale" as EstimateStatus,
    serviceType: "Water Heater Replacement",
    sentAt: ago(20 * DAY),
    followUpAt: ago(10 * DAY),
    expiresAt: futureDate(10 * DAY),
    staleSince: ago(13 * DAY),
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(20 * DAY),
    updatedAt: ago(5 * DAY),
  },
  {
    id: "est_8",
    businessId: "biz_1",
    contactId: "cnt_5",
    opportunityId: null,
    externalId: "EST-1046",
    title: "Dual-Zone Thermostat Upgrade",
    amount: 850,
    status: "open" as EstimateStatus,
    serviceType: "Thermostat Installation",
    sentAt: ago(2 * DAY),
    followUpAt: null,
    expiresAt: futureDate(28 * DAY),
    staleSince: null,
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(2 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "est_9",
    businessId: "biz_1",
    contactId: "cnt_16",
    opportunityId: null,
    externalId: "EST-1040",
    title: "Sump Pump Replacement",
    amount: 1100,
    status: "booked" as EstimateStatus,
    serviceType: "Sump Pump",
    sentAt: ago(10 * DAY),
    followUpAt: null,
    expiresAt: null,
    staleSince: null,
    respondedAt: ago(7 * DAY),
    bookedAt: ago(5 * DAY),
    lostAt: null,
    lostReason: null,
    createdAt: ago(10 * DAY),
    updatedAt: ago(5 * DAY),
  },
  {
    id: "est_10",
    businessId: "biz_1",
    contactId: "cnt_12",
    opportunityId: null,
    externalId: "EST-1032",
    title: "Furnace Replacement - 80K BTU",
    amount: 4800,
    status: "stale" as EstimateStatus,
    serviceType: "Furnace Replacement",
    sentAt: ago(16 * DAY),
    followUpAt: ago(9 * DAY),
    expiresAt: futureDate(14 * DAY),
    staleSince: ago(9 * DAY),
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(16 * DAY),
    updatedAt: ago(9 * DAY),
  },
  {
    id: "est_11",
    businessId: "biz_1",
    contactId: "cnt_21",
    opportunityId: null,
    externalId: "EST-1047",
    title: "Gas Line Repair",
    amount: 380,
    status: "open" as EstimateStatus,
    serviceType: "Gas Line Repair",
    sentAt: ago(1 * DAY),
    followUpAt: null,
    expiresAt: futureDate(29 * DAY),
    staleSince: null,
    respondedAt: null,
    bookedAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: ago(1 * DAY),
    updatedAt: ago(1 * DAY),
  },
];

// ─── CAMPAIGNS ─────────────────────────────────────────

export interface DemoCampaign {
  id: string;
  businessId: string;
  name: string;
  type: CampaignType;
  status: CampaignStatus;
  channel: ChannelType;
  targetSegment: string | null;
  targetCount: number;
  sentCount: number;
  respondedCount: number;
  bookedCount: number;
  revenue: number;
  startAt: Date | null;
  endAt: Date | null;
  stopOnReply: boolean;
  stopOnBooking: boolean;
  createdAt: Date;
  updatedAt: Date;
  steps?: DemoCampaignStep[];
}

export interface DemoCampaignStep {
  id: string;
  campaignId: string;
  stepOrder: number;
  channel: ChannelType;
  templateId: string | null;
  delayMinutes: number;
  subject: string | null;
  body: string;
  createdAt: Date;
}

export const DEMO_CAMPAIGNS: DemoCampaign[] = [
  {
    id: "cmp_1",
    businessId: "biz_1",
    name: "Winter Missed Call Recovery",
    type: "missed_call_followup" as CampaignType,
    status: "active" as CampaignStatus,
    channel: "sms" as ChannelType,
    targetSegment: "Missed calls - last 30 days",
    targetCount: 45,
    sentCount: 38,
    respondedCount: 16,
    bookedCount: 9,
    revenue: 14200,
    startAt: ago(21 * DAY),
    endAt: null,
    stopOnReply: true,
    stopOnBooking: true,
    createdAt: ago(22 * DAY),
    updatedAt: ago(1 * DAY),
    steps: [
      {
        id: "step_1",
        campaignId: "cmp_1",
        stepOrder: 1,
        channel: "sms" as ChannelType,
        templateId: "tpl_1",
        delayMinutes: 5,
        subject: null,
        body: "Hi {{firstName}}, this is {{businessName}}. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
        createdAt: ago(22 * DAY),
      },
      {
        id: "step_2",
        campaignId: "cmp_1",
        stepOrder: 2,
        channel: "sms" as ChannelType,
        templateId: null,
        delayMinutes: 1440,
        subject: null,
        body: "Hi {{firstName}}, just following up from {{businessName}}. We'd love to help with your heating or plumbing needs. Reply BOOK to schedule.",
        createdAt: ago(22 * DAY),
      },
    ],
  },
  {
    id: "cmp_2",
    businessId: "biz_1",
    name: "Q1 Estimate Follow-up",
    type: "estimate_rescue" as CampaignType,
    status: "active" as CampaignStatus,
    channel: "sms" as ChannelType,
    targetSegment: "Stale estimates - 7+ days",
    targetCount: 28,
    sentCount: 24,
    respondedCount: 8,
    bookedCount: 4,
    revenue: 18500,
    startAt: ago(30 * DAY),
    endAt: null,
    stopOnReply: true,
    stopOnBooking: true,
    createdAt: ago(31 * DAY),
    updatedAt: ago(2 * DAY),
    steps: [
      {
        id: "step_3",
        campaignId: "cmp_2",
        stepOrder: 1,
        channel: "sms" as ChannelType,
        templateId: "tpl_2",
        delayMinutes: 0,
        subject: null,
        body: "Hi {{firstName}}, your estimate for {{serviceType}} ({{estimateAmount}}) from {{businessName}} is still available. Any questions? We're happy to help!",
        createdAt: ago(31 * DAY),
      },
      {
        id: "step_4",
        campaignId: "cmp_2",
        stepOrder: 2,
        channel: "sms" as ChannelType,
        templateId: null,
        delayMinutes: 4320,
        subject: null,
        body: "Hi {{firstName}}, just a reminder - your {{serviceType}} estimate expires soon. Reply YES to lock in your price or call (248) 555-1000.",
        createdAt: ago(31 * DAY),
      },
    ],
  },
  {
    id: "cmp_3",
    businessId: "biz_1",
    name: "Spring Maintenance Reactivation",
    type: "reactivation" as CampaignType,
    status: "completed" as CampaignStatus,
    channel: "sms" as ChannelType,
    targetSegment: "No service in 12+ months",
    targetCount: 62,
    sentCount: 62,
    respondedCount: 19,
    bookedCount: 11,
    revenue: 24800,
    startAt: ago(60 * DAY),
    endAt: ago(30 * DAY),
    stopOnReply: true,
    stopOnBooking: true,
    createdAt: ago(65 * DAY),
    updatedAt: ago(30 * DAY),
    steps: [
      {
        id: "step_5",
        campaignId: "cmp_3",
        stepOrder: 1,
        channel: "sms" as ChannelType,
        templateId: "tpl_3",
        delayMinutes: 0,
        subject: null,
        body: "Hi {{firstName}}, it's been a while! {{businessName}} is running a spring maintenance special. Schedule your AC tune-up for just $149. Reply BOOK!",
        createdAt: ago(65 * DAY),
      },
    ],
  },
  {
    id: "cmp_4",
    businessId: "biz_1",
    name: "Emergency HVAC Follow-up",
    type: "missed_call_followup" as CampaignType,
    status: "draft" as CampaignStatus,
    channel: "sms" as ChannelType,
    targetSegment: "After-hours missed calls",
    targetCount: 0,
    sentCount: 0,
    respondedCount: 0,
    bookedCount: 0,
    revenue: 0,
    startAt: null,
    endAt: null,
    stopOnReply: true,
    stopOnBooking: true,
    createdAt: ago(2 * DAY),
    updatedAt: ago(2 * DAY),
    steps: [
      {
        id: "step_6",
        campaignId: "cmp_4",
        stepOrder: 1,
        channel: "sms" as ChannelType,
        templateId: "tpl_1",
        delayMinutes: 0,
        subject: null,
        body: "Hi {{firstName}}, we see you tried to reach {{businessName}} after hours. We're now open! How can we help? Call (248) 555-1000 or reply here.",
        createdAt: ago(2 * DAY),
      },
    ],
  },
];

// ─── TEMPLATES ─────────────────────────────────────────

export interface DemoTemplate {
  id: string;
  businessId: string;
  name: string;
  category: string;
  channel: ChannelType;
  subject: string | null;
  body: string;
  variables: string[];
  isArchived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_TEMPLATES: DemoTemplate[] = [
  {
    id: "tpl_1",
    businessId: "biz_1",
    name: "Missed Call SMS",
    category: "missed_call",
    channel: "sms" as ChannelType,
    subject: null,
    body: "Hi {{firstName}}, this is {{businessName}}. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
    variables: ["firstName", "businessName"],
    isArchived: false,
    createdAt: ago(90 * DAY),
    updatedAt: ago(30 * DAY),
  },
  {
    id: "tpl_2",
    businessId: "biz_1",
    name: "Estimate Follow-up SMS",
    category: "estimate_rescue",
    channel: "sms" as ChannelType,
    subject: null,
    body: "Hi {{firstName}}, your estimate for {{serviceType}} ({{estimateAmount}}) from {{businessName}} is still available. Any questions? We're happy to help!",
    variables: ["firstName", "serviceType", "estimateAmount", "businessName"],
    isArchived: false,
    createdAt: ago(90 * DAY),
    updatedAt: ago(30 * DAY),
  },
  {
    id: "tpl_3",
    businessId: "biz_1",
    name: "Reactivation SMS",
    category: "reactivation",
    channel: "sms" as ChannelType,
    subject: null,
    body: "Hi {{firstName}}, it's been a while since your last visit with {{businessName}}! We'd love to help keep your home comfortable. Reply BOOK to schedule a service.",
    variables: ["firstName", "businessName"],
    isArchived: false,
    createdAt: ago(90 * DAY),
    updatedAt: ago(60 * DAY),
  },
  {
    id: "tpl_4",
    businessId: "biz_1",
    name: "Appointment Confirmation",
    category: "booking",
    channel: "sms" as ChannelType,
    subject: null,
    body: "Hi {{firstName}}, your appointment with {{businessName}} is confirmed for {{appointmentDate}} at {{appointmentTime}}. Reply C to confirm or R to reschedule.",
    variables: ["firstName", "businessName", "appointmentDate", "appointmentTime"],
    isArchived: false,
    createdAt: ago(90 * DAY),
    updatedAt: ago(45 * DAY),
  },
  {
    id: "tpl_5",
    businessId: "biz_1",
    name: "Seasonal Maintenance Email",
    category: "reactivation",
    channel: "email" as ChannelType,
    subject: "Time for your seasonal maintenance checkup!",
    body: "Dear {{firstName}},\n\nIt's that time of year again! {{businessName}} is offering seasonal maintenance specials to keep your home running smoothly.\n\nAs a valued customer, we'd like to offer you priority scheduling. Your last service was {{lastServiceDate}} - staying on top of maintenance helps prevent costly repairs.\n\nSpecial offer: Book your tune-up this month and save {{discountAmount}}!\n\nCall us at (248) 555-1000 or reply to schedule.\n\nBest regards,\nThe {{businessName}} Team",
    variables: ["firstName", "businessName", "lastServiceDate", "discountAmount"],
    isArchived: false,
    createdAt: ago(60 * DAY),
    updatedAt: ago(30 * DAY),
  },
];

// ─── BOOKINGS ──────────────────────────────────────────

export interface DemoBooking {
  id: string;
  businessId: string;
  contactId: string;
  opportunityId: string | null;
  userId: string | null;
  title: string;
  serviceType: string;
  scheduledAt: Date;
  amount: number | null;
  source: BookingSourceType;
  attribution: AttributionMethod;
  notes: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export const DEMO_BOOKINGS: DemoBooking[] = [
  {
    id: "bk_1",
    businessId: "biz_1",
    contactId: "cnt_1",
    opportunityId: "opp_6",
    userId: "usr_1",
    title: "Furnace Annual Tune-Up",
    serviceType: "Furnace Maintenance",
    scheduledAt: futureDate(3 * DAY),
    amount: 250,
    source: "estimate_rescue" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: "Annual maintenance plan customer",
    createdAt: ago(1 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "bk_2",
    businessId: "biz_1",
    contactId: "cnt_2",
    opportunityId: "opp_14",
    userId: "usr_3",
    title: "Drain Cleaning Service",
    serviceType: "Drain Cleaning",
    scheduledAt: futureDate(1 * DAY),
    amount: 350,
    source: "missed_call" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: "Follow-up from missed call recovery",
    createdAt: ago(1 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: "bk_3",
    businessId: "biz_1",
    contactId: "cnt_13",
    opportunityId: "opp_11",
    userId: "usr_3",
    title: "Furnace Inspection",
    serviceType: "Furnace Inspection",
    scheduledAt: futureDate(5 * DAY),
    amount: 150,
    source: "reactivation" as BookingSourceType,
    attribution: "influenced" as AttributionMethod,
    notes: "Reactivated dormant customer",
    createdAt: ago(2 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "bk_4",
    businessId: "biz_1",
    contactId: "cnt_16",
    opportunityId: null,
    userId: "usr_2",
    title: "Sump Pump Replacement",
    serviceType: "Sump Pump",
    scheduledAt: futureDate(2 * DAY),
    amount: 1100,
    source: "manual" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: null,
    createdAt: ago(5 * DAY),
    updatedAt: ago(5 * DAY),
  },
  {
    id: "bk_5",
    businessId: "biz_1",
    contactId: "cnt_20",
    opportunityId: null,
    userId: "usr_1",
    title: "Maintenance Plan Renewal - Full System",
    serviceType: "Maintenance Plan",
    scheduledAt: futureDate(7 * DAY),
    amount: 450,
    source: "manual" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: "VIP customer annual renewal",
    createdAt: ago(2 * DAY),
    updatedAt: ago(2 * DAY),
  },
  {
    id: "bk_6",
    businessId: "biz_1",
    contactId: "cnt_5",
    opportunityId: null,
    userId: "usr_2",
    title: "Thermostat Upgrade - Dual Zone",
    serviceType: "Thermostat Installation",
    scheduledAt: futureDate(4 * DAY),
    amount: 850,
    source: "manual" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: "Upgrading to smart thermostat",
    createdAt: ago(1.5 * DAY),
    updatedAt: ago(1.5 * DAY),
  },
  {
    id: "bk_7",
    businessId: "biz_1",
    contactId: "cnt_9",
    opportunityId: null,
    userId: "usr_3",
    title: "Kitchen Drain Cleaning",
    serviceType: "Drain Cleaning",
    scheduledAt: ago(3 * DAY),
    amount: 300,
    source: "missed_call" as BookingSourceType,
    attribution: "direct" as AttributionMethod,
    notes: "Completed",
    createdAt: ago(6 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: "bk_8",
    businessId: "biz_1",
    contactId: "cnt_12",
    opportunityId: null,
    userId: "usr_1",
    title: "Furnace Diagnostic",
    serviceType: "Furnace Repair",
    scheduledAt: ago(5 * DAY),
    amount: 175,
    source: "reactivation" as BookingSourceType,
    attribution: "influenced" as AttributionMethod,
    notes: "Completed - recommended full replacement",
    createdAt: ago(8 * DAY),
    updatedAt: ago(5 * DAY),
  },
];

// ─── ACTIVITY ──────────────────────────────────────────

export const DEMO_ACTIVITY: ActivityItem[] = [
  {
    id: "act_1",
    type: "sms_sent",
    description: "SMS sent to Thomas Jankowski - missed call follow-up",
    timestamp: ago(0.25 * DAY),
    entityType: "opportunity",
    entityId: "opp_4",
    userName: "System",
  },
  {
    id: "act_2",
    type: "opportunity_created",
    description: "Opportunity created from missed call - Thomas Jankowski",
    timestamp: ago(0.5 * DAY),
    entityType: "opportunity",
    entityId: "opp_4",
    userName: "System",
  },
  {
    id: "act_3",
    type: "booking_confirmed",
    description: "Booking confirmed for drain cleaning - Maria Gonzalez",
    timestamp: ago(1 * DAY),
    entityType: "booking",
    entityId: "bk_2",
    userName: "Jake Morrison",
  },
  {
    id: "act_4",
    type: "status_change",
    description: "Opportunity 'Missed call - drain clog' moved to Booked",
    timestamp: ago(1 * DAY),
    entityType: "opportunity",
    entityId: "opp_14",
    userName: "Mike Reynolds",
  },
  {
    id: "act_5",
    type: "booking_confirmed",
    description: "Booking confirmed for furnace tune-up - John Kowalski",
    timestamp: ago(1 * DAY),
    entityType: "booking",
    entityId: "bk_1",
    userName: "Mike Reynolds",
  },
  {
    id: "act_6",
    type: "sms_received",
    description: "SMS reply received from William Foster - 'Yes, I need help with my water heater'",
    timestamp: ago(1.5 * DAY),
    entityType: "opportunity",
    entityId: "opp_3",
    userName: undefined,
  },
  {
    id: "act_7",
    type: "estimate_stale",
    description: "Estimate EST-1042 for AC replacement is now 14 days stale",
    timestamp: ago(2 * DAY),
    entityType: "estimate",
    entityId: "est_1",
    userName: "System",
  },
  {
    id: "act_8",
    type: "booking_confirmed",
    description: "Booking confirmed for furnace inspection - Daniel Abrams",
    timestamp: ago(2 * DAY),
    entityType: "booking",
    entityId: "bk_3",
    userName: "Jake Morrison",
  },
  {
    id: "act_9",
    type: "opportunity_lost",
    description: "Opportunity 'Stale estimate - AC repair' marked as Lost - competitor",
    timestamp: ago(2 * DAY),
    entityType: "opportunity",
    entityId: "opp_8",
    userName: "Sarah Chen",
  },
  {
    id: "act_10",
    type: "sms_sent",
    description: "SMS sent to David Kim - missed call recovery",
    timestamp: ago(1 * DAY + 1 * HOUR),
    entityType: "opportunity",
    entityId: "opp_1",
    userName: "System",
  },
  {
    id: "act_11",
    type: "note_added",
    description: "Note added to opportunity - Patricia Murphy interested in full HVAC install",
    timestamp: ago(3 * DAY),
    entityType: "opportunity",
    entityId: "opp_10",
    userName: "Mike Reynolds",
  },
  {
    id: "act_12",
    type: "campaign_started",
    description: "Campaign 'Winter Missed Call Recovery' sent 12 new messages",
    timestamp: ago(3 * DAY),
    entityType: "campaign",
    entityId: "cmp_1",
    userName: "System",
  },
  {
    id: "act_13",
    type: "sms_sent",
    description: "SMS sent to Robert Thompson - reactivation outreach",
    timestamp: ago(6 * DAY),
    entityType: "opportunity",
    entityId: "opp_9",
    userName: "System",
  },
  {
    id: "act_14",
    type: "contact_created",
    description: "New contact created - David Kim (from missed call)",
    timestamp: ago(1 * DAY),
    entityType: "contact",
    entityId: "cnt_7",
    userName: "System",
  },
  {
    id: "act_15",
    type: "status_change",
    description: "Opportunity 'Stale estimate - bathroom remodel' moved to Qualified",
    timestamp: ago(3 * DAY),
    entityType: "opportunity",
    entityId: "opp_7",
    userName: "Sarah Chen",
  },
  {
    id: "act_16",
    type: "sms_received",
    description: "SMS reply received from Patricia Murphy - 'Yes, we need a quote for our new home'",
    timestamp: ago(4 * DAY),
    entityType: "opportunity",
    entityId: "opp_10",
    userName: undefined,
  },
];

// ─── ALERTS ────────────────────────────────────────────

export const DEMO_ALERTS: Alert[] = [
  {
    id: "alert_1",
    type: "warning",
    title: "3 missed calls in the last hour",
    description: "There are 3 unanswered calls from the past hour that need follow-up.",
    createdAt: ago(0.5 * HOUR),
    isRead: false,
  },
  {
    id: "alert_2",
    type: "warning",
    title: "Estimate #1042 is now 14 days stale",
    description: "The AC replacement estimate for Steven Bakshi has not received a response in 14 days.",
    createdAt: ago(2 * HOUR),
    isRead: false,
  },
  {
    id: "alert_3",
    type: "success",
    title: "Campaign 'Winter Recovery' achieved 42% response rate",
    description: "The Winter Missed Call Recovery campaign has exceeded the 30% response rate benchmark.",
    createdAt: ago(6 * HOUR),
    isRead: true,
  },
  {
    id: "alert_4",
    type: "error",
    title: "Twilio balance below $25",
    description: "Your Twilio account balance is low. Add funds to avoid service interruption.",
    createdAt: ago(1 * DAY),
    isRead: false,
  },
  {
    id: "alert_5",
    type: "info",
    title: "5 new opportunities created today",
    description: "3 from missed calls, 1 from stale estimates, and 1 from reactivation campaigns.",
    createdAt: ago(4 * HOUR),
    isRead: true,
  },
];

// ─── REPORT SNAPSHOTS ──────────────────────────────────

export const DEMO_REPORT_SNAPSHOTS = {
  weekly: {
    id: "rpt_1",
    businessId: "biz_1",
    reportType: "weekly_summary",
    periodStart: ago(7 * DAY),
    periodEnd: new Date(),
    data: {
      totalRevenue: 32700,
      totalOpportunities: 18,
      totalBookings: 9,
      missedCallRecoveryRate: 0.42,
      estimateRescueRate: 0.33,
      reactivationRate: 0.31,
      avgResponseTimeMinutes: 4.2,
      topServiceType: "Furnace Repair",
    },
    createdAt: new Date(),
  },
  monthly: {
    id: "rpt_2",
    businessId: "biz_1",
    reportType: "monthly_summary",
    periodStart: ago(30 * DAY),
    periodEnd: new Date(),
    data: {
      totalRevenue: 127850,
      totalOpportunities: 67,
      totalBookings: 34,
      missedCallRecoveryRate: 0.38,
      estimateRescueRate: 0.29,
      reactivationRate: 0.27,
      avgResponseTimeMinutes: 5.1,
      topServiceType: "AC Installation",
    },
    createdAt: new Date(),
  },
};

// ─── REACTIVATION SEGMENTS ─────────────────────────────

export const DEMO_REACTIVATION_SEGMENTS: ReactivationSegment[] = [
  {
    id: "seg_1",
    name: "No Service in 12+ Months",
    description: "Customers who haven't had any service in over a year",
    contactCount: 47,
    estimatedValue: 82500,
    criteria: "lastServiceAt < 12 months ago",
  },
  {
    id: "seg_2",
    name: "Maintenance Due",
    description: "Customers with maintenance plans due for seasonal service",
    contactCount: 31,
    estimatedValue: 18600,
    criteria: "tags includes 'maintenance-plan' AND lastServiceAt < 6 months ago",
  },
  {
    id: "seg_3",
    name: "Membership Renewal",
    description: "Customers whose annual membership is up for renewal",
    contactCount: 12,
    estimatedValue: 7200,
    criteria: "tags includes 'maintenance-plan' AND membershipExpires < 30 days",
  },
  {
    id: "seg_4",
    name: "Replacement Cycle Candidates",
    description: "Customers with equipment nearing end of typical lifespan",
    contactCount: 8,
    estimatedValue: 96000,
    criteria: "equipment age > 15 years OR tagged 'replacement-candidate'",
  },
];

// ─── DASHBOARD KPIS ────────────────────────────────────

export const DEMO_DASHBOARD_KPIS = {
  revenueInfluenced: 127850,
  opportunitiesRecovered: 34,
  bookingsCreated: 22,
  avgResponseTime: 4.2,
  estimatesReopened: 11,
  customersReactivated: 8,
};

// ─── WORKFLOW PERFORMANCE ──────────────────────────────

export const DEMO_WORKFLOW_PERFORMANCE: WorkflowPerformanceData[] = [
  {
    workflow: "Missed Call Recovery",
    opportunities: 45,
    recovered: 19,
    revenue: 42300,
  },
  {
    workflow: "Estimate Rescue",
    opportunities: 28,
    recovered: 9,
    revenue: 54200,
  },
  {
    workflow: "Customer Reactivation",
    opportunities: 62,
    recovered: 17,
    revenue: 31350,
  },
];

// ─── RECOVERY TREND ────────────────────────────────────

export const DEMO_RECOVERY_TREND: RecoveryTrendData[] = Array.from(
  { length: 14 },
  (_, i) => ({
    date: dateStr(13 - i),
    missedCall: Math.floor(Math.random() * 4) + 1,
    estimateRescue: Math.floor(Math.random() * 3),
    reactivation: Math.floor(Math.random() * 3),
  })
);

// Seed with deterministic-ish values so they don't change on every import
const _trendValues: [number, number, number][] = [
  [2, 1, 0], [3, 0, 1], [1, 2, 2], [4, 1, 1],
  [2, 3, 0], [3, 1, 2], [1, 0, 1], [5, 2, 3],
  [2, 1, 1], [3, 2, 0], [4, 1, 2], [2, 3, 1],
  [3, 0, 2], [4, 2, 1],
];

for (let i = 0; i < 14; i++) {
  DEMO_RECOVERY_TREND[i].missedCall = _trendValues[i][0];
  DEMO_RECOVERY_TREND[i].estimateRescue = _trendValues[i][1];
  DEMO_RECOVERY_TREND[i].reactivation = _trendValues[i][2];
}

// ─── INTEGRATIONS ──────────────────────────────────────

export const DEMO_INTEGRATIONS: IntegrationCard[] = [
  {
    provider: "twilio",
    name: "Twilio",
    description: "SMS messaging and call tracking",
    icon: "MessageSquare",
    status: "connected",
    lastSyncAt: ago(5 * 60 * 1000),
  },
  {
    provider: "jobber",
    name: "Jobber",
    description: "Field service management and scheduling",
    icon: "Briefcase",
    status: "disconnected",
  },
  {
    provider: "housecall_pro",
    name: "Housecall Pro",
    description: "Home service business management",
    icon: "Home",
    status: "disconnected",
  },
  {
    provider: "servicetitan",
    name: "ServiceTitan",
    description: "Enterprise field service software",
    icon: "Building2",
    status: "disconnected",
  },
  {
    provider: "gmail",
    name: "Gmail",
    description: "Email sending and receiving via Gmail",
    icon: "Mail",
    status: "connected",
    lastSyncAt: ago(15 * 60 * 1000),
  },
  {
    provider: "outlook",
    name: "Outlook",
    description: "Email sending and receiving via Outlook",
    icon: "Mail",
    status: "disconnected",
  },
  {
    provider: "google_calendar",
    name: "Google Calendar",
    description: "Appointment scheduling and sync",
    icon: "Calendar",
    status: "connected",
    lastSyncAt: ago(10 * 60 * 1000),
  },
  {
    provider: "csv",
    name: "CSV Import",
    description: "Import contacts and estimates from CSV files",
    icon: "FileSpreadsheet",
    status: "connected",
    lastSyncAt: ago(2 * DAY),
  },
];
