import type {
  Booking,
  CallEvent,
  Campaign,
  MessageEvent,
  Opportunity,
  ReactivationSegmentKey,
} from "@/types/domain";
import {
  BUSINESS_ID,
  LOCATION_ID,
  OWNER_ID,
  addActivity,
  at,
  determineSegment,
  ensureEstimateOpportunity,
  getContact,
  getOpportunity,
  getStore,
  getUser,
  iso,
  nameOf,
  nextId,
  setOpportunityStatus,
} from "@/lib/demo-data";
import { twilioMockService } from "@/services/twilio-mock-service";

const replyBodies = [
  "Tomorrow morning is perfect.",
  "Do you have an afternoon slot?",
  "Can you text me the first available appointment?",
  "Yes, I still need help with this.",
];

function nowIso() {
  return iso(new Date());
}

function appendInboundMessage(contactId: string, opportunityId: string, body: string) {
  const message: MessageEvent = {
    id: nextId("msg"),
    businessId: BUSINESS_ID,
    contactId,
    opportunityId,
    direction: "inbound",
    channel: "sms",
    body,
    deliveryStatus: "received",
    receivedAt: nowIso(),
  };

  getStore().messageEvents.unshift(message);
  return message;
}

export const opportunityService = {
  simulateMissedInboundCall() {
    const store = getStore();
    const now = new Date();
    const scenarios = ["+13135551007", "+13135551018", "+13135551999", "+13135551024", "+13135551003"];
    const phone = scenarios[(globalThis.revenueLeakSequence ?? 500) % scenarios.length];
    let contact = store.contacts.find((row) => row.phone === phone);

    if (!contact) {
      contact = {
        id: nextId("contact"),
        businessId: BUSINESS_ID,
        locationId: LOCATION_ID,
        firstName: "New",
        lastName: `Caller ${(globalThis.revenueLeakSequence ?? 500) - 499}`,
        phone,
        tags: ["new-lead", "missed-call"],
        lifecycleStage: "lead",
        notes: "Created from missed inbound call workflow.",
      };
      store.contacts.unshift(contact);
    }

    const recent = store.opportunities.find((row) => {
      if (row.type !== "missed_call" || row.contactId !== contact.id) {
        return false;
      }

      const ageHours = (now.getTime() - new Date(row.createdAt).getTime()) / 3_600_000;
      return ageHours <= store.business.duplicateMissedCallWindowHours && ["open", "attempted", "responded"].includes(row.status);
    });

    const opportunity =
      recent ??
      (() => {
        const created: Opportunity = {
          id: nextId("opp_mc"),
          businessId: BUSINESS_ID,
          contactId: contact.id,
          ownerUserId: "user_csr",
          type: "missed_call",
          status: "open",
          title: `Missed call - ${nameOf(contact)}`,
          description: "Generated by mocked inbound missed-call workflow.",
          priority: "medium",
          valueCents: 15800,
          directRevenueCents: 0,
          influencedRevenueCents: 15800,
          sourceLabel: "Inbound phone",
          createdAt: iso(now),
          updatedAt: iso(now),
          lastTouchedAt: iso(now),
        };

        store.opportunities.unshift(created);
        return created;
      })();

    opportunity.updatedAt = iso(now);
    opportunity.lastTouchedAt = iso(now);

    if (opportunity.status === "lost") {
      opportunity.status = "open";
    }

    const callEvent: CallEvent = {
      id: nextId("call"),
      businessId: BUSINESS_ID,
      contactId: contact.id,
      opportunityId: opportunity.id,
      fromPhone: contact.phone,
      toPhone: "+13135550100",
      direction: "inbound",
      disposition: now.getHours() < 8 || now.getHours() > 17 ? "after_hours" : "missed",
      durationSeconds: 19,
      afterHours: now.getHours() < 8 || now.getHours() > 17,
      startedAt: iso(now),
      summary: "Mock inbound call arrived and was routed into the missed-call workflow.",
      smsPreview: "Auto-reply dispatched with booking CTA.",
      bookingLogged: false,
    };

    store.callEvents.unshift(callEvent);
    twilioMockService.sendSms({
      contactId: contact.id,
      opportunityId: opportunity.id,
      templateId: "template_missed_call_sms",
      body: `Hi ${contact.firstName}, sorry we missed your call. Reply here and our team can help you book service right away.`,
    });

    addActivity({
      type: "call_captured",
      title: `Missed inbound call captured for ${nameOf(contact)}`,
      detail: recent ? "Existing opportunity updated inside the suppression window." : "New missed-call opportunity created and initial SMS sent.",
      entityType: "opportunity",
      entityId: opportunity.id,
    });

    return { contact, opportunity, callEvent };
  },

  simulateReply(opportunityId?: string) {
    const store = getStore();
    const opportunity =
      (opportunityId ? getOpportunity(opportunityId) : undefined) ??
      store.opportunities.find(
        (row) =>
          row.type === "missed_call" &&
          ["open", "attempted", "responded"].includes(row.status) &&
          store.messageEvents.some((message) => message.opportunityId === row.id && message.direction === "outbound"),
      );

    if (!opportunity) {
      return null;
    }

    const contact = getContact(opportunity.contactId);

    if (!contact) {
      return null;
    }

    const body = replyBodies[(globalThis.revenueLeakSequence ?? 500) % replyBodies.length];
    const message = appendInboundMessage(contact.id, opportunity.id, body);

    setOpportunityStatus(opportunity, "responded");

    const call = store.callEvents.find((row) => row.opportunityId === opportunity.id);
    if (call) {
      call.disposition = "responded";
      call.respondedAt = nowIso();
      call.smsPreview = body;
    }

    addActivity({
      type: "message_received",
      title: `${nameOf(contact)} replied to the missed-call SMS`,
      detail: body,
      entityType: "message",
      entityId: message.id,
    });

    return { contact, opportunity, message };
  },

  logBooking(opportunityId?: string) {
    const store = getStore();
    const opportunity =
      (opportunityId ? getOpportunity(opportunityId) : undefined) ??
      store.opportunities.find((row) => ["responded", "open", "attempted"].includes(row.status));

    if (!opportunity) {
      return null;
    }

    const contact = getContact(opportunity.contactId);
    if (!contact) {
      return null;
    }

    const booking: Booking = {
      id: nextId("booking"),
      businessId: BUSINESS_ID,
      contactId: contact.id,
      opportunityId: opportunity.id,
      bookedAt: nowIso(),
      serviceDate: iso(at(new Date(), { days: 5 })),
      valueCents: opportunity.valueCents,
      status: "scheduled",
      source: opportunity.type,
      notes: `Created from ${opportunity.type} workflow.`,
    };

    store.bookings.unshift(booking);
    opportunity.directRevenueCents = opportunity.valueCents;
    opportunity.influencedRevenueCents = Math.max(opportunity.influencedRevenueCents, opportunity.valueCents);
    setOpportunityStatus(opportunity, "booked");

    const call = store.callEvents.find((row) => row.opportunityId === opportunity.id);
    if (call) {
      call.disposition = "booked";
      call.bookedAt = booking.bookedAt;
      call.bookingLogged = true;
    }

    const estimate = store.estimates.find((row) => row.opportunityId === opportunity.id);
    if (estimate) {
      estimate.status = "booked";
      estimate.bookedAt = booking.bookedAt;
      estimate.enrolledInFollowUp = true;
    }

    addActivity({
      type: "booking_created",
      title: `Booking created from ${opportunity.type.replace("_", " ")}`,
      detail: `${nameOf(contact)} booked for ${Math.round(opportunity.valueCents / 100)} dollars in influenced value.`,
      entityType: "booking",
      entityId: booking.id,
    });

    return { contact, opportunity, booking };
  },

  enrollEstimateFollowUp(estimateId?: string) {
    const store = getStore();
    const estimate =
      (estimateId ? store.estimates.find((row) => row.id === estimateId) : undefined) ??
      store.estimates.find((row) => row.status === "stale" || (row.status === "open" && row.staleSince));

    if (!estimate) {
      return null;
    }

    const contact = getContact(estimate.contactId);
    const opportunity = ensureEstimateOpportunity(estimate);

    estimate.enrolledInFollowUp = true;
    estimate.status = "enrolled";

    twilioMockService.sendSms({
      contactId: estimate.contactId,
      opportunityId: opportunity.id,
      templateId: "template_estimate_rescue_sms",
      body: `Hi ${contact?.firstName ?? "there"}, your ${estimate.serviceType} estimate is still open. Want help comparing options or booking next steps?`,
    });

    setOpportunityStatus(opportunity, "attempted");
    addActivity({
      type: "estimate_enrolled",
      title: `Estimate ${estimate.number} enrolled in follow-up`,
      detail: `${estimate.serviceType} created or updated an estimate_rescue opportunity.`,
      entityType: "estimate",
      entityId: estimate.id,
    });

    return { estimate, opportunity };
  },

  markEstimateOutcome(estimateId: string, outcome: "responded" | "booked" | "lost") {
    const estimate = getStore().estimates.find((row) => row.id === estimateId);
    if (!estimate) {
      return null;
    }

    const opportunity = ensureEstimateOpportunity(estimate);
    const now = nowIso();

    if (outcome === "responded") {
      estimate.status = "responded";
      estimate.respondedAt = now;
      setOpportunityStatus(opportunity, "responded");
    }

    if (outcome === "booked") {
      estimate.status = "booked";
      estimate.bookedAt = now;
      this.logBooking(opportunity.id);
    }

    if (outcome === "lost") {
      estimate.status = "lost";
      estimate.lostAt = now;
      setOpportunityStatus(opportunity, "lost", true);
    }

    addActivity({
      type: "opportunity_updated",
      title: `Estimate ${estimate.number} marked ${outcome}`,
      detail: `Opportunity ${opportunity.id} moved to ${outcome}.`,
      entityType: "estimate",
      entityId: estimate.id,
    });

    return { estimate, opportunity };
  },

  launchReactivationCampaign(segmentKey: ReactivationSegmentKey) {
    const store = getStore();
    const now = new Date();
    const campaign =
      store.campaigns.find((row) => row.segmentKey === segmentKey) ??
      (() => {
        const created: Campaign = {
          id: nextId("campaign"),
          businessId: BUSINESS_ID,
          name: `Reactivation - ${segmentKey.replaceAll("_", " ")}`,
          type: "reactivation",
          status: "draft",
          audienceLabel: segmentKey.replaceAll("_", " "),
          segmentKey,
          createdAt: iso(now),
          updatedAt: iso(now),
        };

        store.campaigns.unshift(created);
        store.campaignSteps.push({
          id: nextId("step"),
          campaignId: created.id,
          stepOrder: 1,
          channel: "sms",
          delayHours: 0,
          templateId: "template_membership_sms",
          bodyPreview: "Initial reactivation outreach.",
        });

        return created;
      })();

    campaign.status = "active";
    campaign.launchedAt = campaign.launchedAt ?? iso(now);
    campaign.updatedAt = iso(now);

    let createdCount = 0;
    for (const contact of store.contacts.filter((row) => determineSegment(row) === segmentKey)) {
      const existing = store.opportunities.find(
        (row) => row.type === "reactivation" && row.contactId === contact.id && ["open", "attempted", "responded", "booked"].includes(row.status),
      );

      if (existing) {
        continue;
      }

      createdCount += 1;
      const opportunity: Opportunity = {
        id: nextId("opp_re"),
        businessId: BUSINESS_ID,
        contactId: contact.id,
        ownerUserId: OWNER_ID,
        campaignId: campaign.id,
        type: "reactivation",
        status: "open",
        title: `Reactivation - ${nameOf(contact)}`,
        description: `Created from ${segmentKey.replaceAll("_", " ")} segment.`,
        priority: contact.tags.includes("vip") ? "high" : "medium",
        valueCents: contact.tags.includes("replacement-cycle") ? 1150000 : 26900,
        directRevenueCents: 0,
        influencedRevenueCents: contact.tags.includes("replacement-cycle") ? 1150000 : 26900,
        sourceLabel: segmentKey.replaceAll("_", " "),
        createdAt: iso(now),
        updatedAt: iso(now),
        lastTouchedAt: iso(now),
      };

      store.opportunities.unshift(opportunity);
      twilioMockService.sendSms({
        contactId: contact.id,
        opportunityId: opportunity.id,
        templateId: "template_membership_sms",
        body: `Hi ${contact.firstName}, we have a priority service opening this week and wanted to see if you would like us to hold it for you.`,
      });
    }

    addActivity({
      type: "campaign_launched",
      title: `Reactivation campaign launched for ${segmentKey.replaceAll("_", " ")}`,
      detail: `${createdCount} opportunities created or refreshed from the selected segment.`,
      entityType: "campaign",
      entityId: campaign.id,
    });

    return { campaign, createdCount };
  },

  assignOpportunityOwner(opportunityId: string, ownerUserId: string) {
    const opportunity = getOpportunity(opportunityId);
    if (!opportunity) {
      return null;
    }

    opportunity.ownerUserId = ownerUserId;
    opportunity.updatedAt = nowIso();
    addActivity({
      type: "opportunity_updated",
      title: "Opportunity owner changed",
      detail: `Assigned to ${getUser(ownerUserId)?.name ?? ownerUserId}.`,
      entityType: "opportunity",
      entityId: opportunity.id,
    });

    return opportunity;
  },

  getInboxSummary() {
    const store = getStore();
    return store.callEvents.map((call) => ({
      ...call,
      contact: call.contactId ? getContact(call.contactId) : undefined,
      opportunity: call.opportunityId ? getOpportunity(call.opportunityId) : undefined,
      recentMessages: call.opportunityId ? store.messageEvents.filter((message) => message.opportunityId === call.opportunityId).slice(0, 4) : [],
    }));
  },

  getHighPriorityOpenOpportunities() {
    return getStore().opportunities.filter((opportunity) => opportunity.priority === "high" && ["open", "attempted", "responded"].includes(opportunity.status));
  },
};
