export {
  demoBusiness,
  demoUsers,
  demoContacts,
  demoOpportunities,
  demoCallEvents,
  demoEstimates,
  demoTemplates,
  demoCampaigns,
  demoMessages,
  demoBookings,
  demoActivityLogs,
  demoReportSnapshots,
  demoIntegrations,
  dashboardSummary,
  demoAlerts,
  getContactById,
  getUserById,
  getOpportunitiesForContact,
  getMessagesForOpportunity,
} from "@/lib/demo-data";
