import { PrismaClient } from "@prisma/client";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

function ago(ms: number): Date {
  return new Date(Date.now() - ms);
}

function future(ms: number): Date {
  return new Date(Date.now() + ms);
}

async function seed() {
  console.log("🌱 Starting seed...\n");

  // ── Clear existing data (reverse FK order) ──────────────
  console.log("  Clearing existing data...");
  await prisma.activityLog.deleteMany();
  await prisma.reportSnapshot.deleteMany();
  await prisma.integrationConnection.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.messageEvent.deleteMany();
  await prisma.campaignStep.deleteMany();
  await prisma.campaign.deleteMany();
  await prisma.template.deleteMany();
  await prisma.estimate.deleteMany();
  await prisma.callEvent.deleteMany();
  await prisma.opportunityNote.deleteMany();
  await prisma.opportunity.deleteMany();
  await prisma.contact.deleteMany();
  await prisma.location.deleteMany();
  await prisma.user.deleteMany();
  await prisma.business.deleteMany();
  console.log("  ✓ Cleared\n");

  // ── Business ────────────────────────────────────────────
  console.log("  Creating business...");
  const business = await prisma.business.create({
    data: {
      id: "biz_1",
      name: "North Shore Heating & Plumbing",
      industry: "multi_trade",
      timezone: "America/Detroit",
      staleEstimateDays: 7,
      attributionWindowDays: 14,
      highValueThreshold: 2500,
      missedCallSuppressionMinutes: 240,
      phone: "+12485551000",
      email: "info@northshoreheating.com",
      website: "https://northshoreheating.com",
      logoUrl: null,
      address: "4820 Woodward Ave",
      city: "Royal Oak",
      state: "MI",
      zip: "48073",
      createdAt: ago(180 * DAY),
    },
  });
  console.log(`  ✓ Business: ${business.name}\n`);

  // ── Users ───────────────────────────────────────────────
  console.log("  Creating users...");
  const users = await Promise.all([
    prisma.user.create({
      data: {
        id: "usr_1",
        businessId: business.id,
        email: "mike@northshoreheating.com",
        name: "Mike Reynolds",
        role: "owner",
        phone: "+12485551001",
        passwordHash: "demo",
        isActive: true,
        lastLoginAt: ago(0.5 * HOUR),
        createdAt: ago(180 * DAY),
      },
    }),
    prisma.user.create({
      data: {
        id: "usr_2",
        businessId: business.id,
        email: "sarah@northshoreheating.com",
        name: "Sarah Chen",
        role: "manager",
        phone: "+12485551002",
        passwordHash: "demo",
        isActive: true,
        lastLoginAt: ago(2 * HOUR),
        createdAt: ago(160 * DAY),
      },
    }),
    prisma.user.create({
      data: {
        id: "usr_3",
        businessId: business.id,
        email: "jake@northshoreheating.com",
        name: "Jake Morrison",
        role: "csr",
        phone: "+12485551003",
        passwordHash: "demo",
        isActive: true,
        lastLoginAt: ago(1 * HOUR),
        createdAt: ago(120 * DAY),
      },
    }),
  ]);
  console.log(`  ✓ Users: ${users.length}\n`);

  // ── Location ────────────────────────────────────────────
  console.log("  Creating location...");
  await prisma.location.create({
    data: {
      id: "loc_1",
      businessId: business.id,
      name: "Main Office",
      address: "4820 Woodward Ave",
      city: "Royal Oak",
      state: "MI",
      zip: "48073",
      phone: "+12485551000",
      isDefault: true,
      createdAt: ago(180 * DAY),
    },
  });
  console.log("  ✓ Location: Main Office\n");

  // ── Contacts ────────────────────────────────────────────
  console.log("  Creating contacts...");
  const contactsData: Parameters<typeof prisma.contact.create>[0]["data"][] = [
    {
      id: "cnt_1",
      businessId: business.id,
      firstName: "John",
      lastName: "Kowalski",
      email: "john.kowalski@gmail.com",
      phone: "+12485559101",
      type: "customer",
      status: "active",
      address: "312 Maple St",
      city: "Royal Oak",
      state: "MI",
      zip: "48067",
      tags: ["furnace", "maintenance-plan"],
      source: "referral",
      lastServiceAt: ago(45 * DAY),
      lifetime_value: 4200,
      notes: "Preferred customer, has maintenance plan",
      createdAt: ago(400 * DAY),
    },
    {
      id: "cnt_2",
      businessId: business.id,
      firstName: "Maria",
      lastName: "Gonzalez",
      email: "maria.g@outlook.com",
      phone: "+13135559202",
      type: "customer",
      status: "active",
      address: "8901 Livernois Ave",
      city: "Detroit",
      state: "MI",
      zip: "48204",
      tags: ["plumbing", "water-heater"],
      source: "website",
      lastServiceAt: ago(20 * DAY),
      lifetime_value: 3100,
      createdAt: ago(300 * DAY),
    },
    {
      id: "cnt_3",
      businessId: business.id,
      firstName: "Robert",
      lastName: "Thompson",
      email: "rthompson@yahoo.com",
      phone: "+15865559303",
      type: "former_customer",
      status: "dormant",
      address: "1445 Gratiot Ave",
      city: "Clinton Township",
      state: "MI",
      zip: "48035",
      tags: ["hvac", "duct-cleaning"],
      source: "google",
      lastServiceAt: ago(380 * DAY),
      lifetime_value: 1800,
      notes: "Had furnace installed 2022",
      createdAt: ago(700 * DAY),
    },
    {
      id: "cnt_4",
      businessId: business.id,
      firstName: "Lisa",
      lastName: "Patel",
      email: "lisa.patel@gmail.com",
      phone: "+12485559404",
      type: "lead",
      status: "active",
      address: "2200 Cole St",
      city: "Birmingham",
      state: "MI",
      zip: "48009",
      tags: ["ac-install"],
      source: "missed_call",
      lifetime_value: 0,
      createdAt: ago(3 * DAY),
    },
    {
      id: "cnt_5",
      businessId: business.id,
      firstName: "James",
      lastName: "O'Brien",
      email: "jobrien@comcast.net",
      phone: "+12485559505",
      type: "customer",
      status: "active",
      address: "555 Woodward Heights",
      city: "Ferndale",
      state: "MI",
      zip: "48220",
      tags: ["furnace", "ac", "maintenance-plan"],
      source: "referral",
      lastServiceAt: ago(90 * DAY),
      lifetime_value: 8700,
      notes: "Long-time customer, two systems",
      createdAt: ago(900 * DAY),
    },
    {
      id: "cnt_6",
      businessId: business.id,
      firstName: "Angela",
      lastName: "Williams",
      email: "awilliams@gmail.com",
      phone: "+13135559606",
      type: "customer",
      status: "active",
      address: "780 Lakeshore Dr",
      city: "Grosse Pointe",
      state: "MI",
      zip: "48230",
      tags: ["plumbing", "bathroom-remodel"],
      source: "website",
      lastServiceAt: ago(15 * DAY),
      lifetime_value: 6200,
      createdAt: ago(500 * DAY),
    },
    {
      id: "cnt_7",
      businessId: business.id,
      firstName: "David",
      lastName: "Kim",
      email: "dkim@gmail.com",
      phone: "+15865559707",
      type: "lead",
      status: "active",
      address: "3300 Rochester Rd",
      city: "Troy",
      state: "MI",
      zip: "48083",
      tags: ["furnace-repair"],
      source: "google",
      notes: "Called about furnace not heating",
      lifetime_value: 0,
      createdAt: ago(1 * DAY),
    },
    {
      id: "cnt_8",
      businessId: business.id,
      firstName: "Patricia",
      lastName: "Murphy",
      email: "pmurphy@att.net",
      phone: "+12485559808",
      type: "former_customer",
      status: "dormant",
      address: "920 Crooks Rd",
      city: "Clawson",
      state: "MI",
      zip: "48017",
      tags: ["furnace", "ac"],
      source: "referral",
      lastServiceAt: ago(420 * DAY),
      lifetime_value: 5500,
      notes: "Moved to new home, may need new install",
      createdAt: ago(800 * DAY),
    },
    {
      id: "cnt_9",
      businessId: business.id,
      firstName: "Michael",
      lastName: "Russo",
      email: "mrusso@hotmail.com",
      phone: "+13135559909",
      type: "customer",
      status: "active",
      address: "6145 Michigan Ave",
      city: "Dearborn",
      state: "MI",
      zip: "48126",
      tags: ["plumbing", "drain-cleaning"],
      source: "google",
      lastServiceAt: ago(60 * DAY),
      lifetime_value: 2400,
      createdAt: ago(350 * DAY),
    },
    {
      id: "cnt_10",
      businessId: business.id,
      firstName: "Jennifer",
      lastName: "Chang",
      email: "jchang@gmail.com",
      phone: "+12485550010",
      type: "customer",
      status: "active",
      address: "1100 S Adams Rd",
      city: "Birmingham",
      state: "MI",
      zip: "48009",
      tags: ["ac", "maintenance-plan"],
      source: "website",
      lastServiceAt: ago(30 * DAY),
      lifetime_value: 3600,
      createdAt: ago(450 * DAY),
    },
    {
      id: "cnt_11",
      businessId: business.id,
      firstName: "William",
      lastName: "Foster",
      phone: "+15865550011",
      type: "lead",
      status: "active",
      address: "2750 Van Dyke Ave",
      city: "Warren",
      state: "MI",
      zip: "48093",
      tags: ["water-heater"],
      source: "missed_call",
      lifetime_value: 0,
      createdAt: ago(2 * DAY),
    },
    {
      id: "cnt_12",
      businessId: business.id,
      firstName: "Susan",
      lastName: "Novak",
      email: "snovak@gmail.com",
      phone: "+12485550012",
      type: "customer",
      status: "active",
      address: "430 W Lincoln Ave",
      city: "Royal Oak",
      state: "MI",
      zip: "48067",
      tags: ["furnace", "humidifier"],
      source: "referral",
      lastServiceAt: ago(100 * DAY),
      lifetime_value: 4800,
      notes: "Referred by John Kowalski",
      createdAt: ago(600 * DAY),
    },
    {
      id: "cnt_13",
      businessId: business.id,
      firstName: "Daniel",
      lastName: "Abrams",
      email: "dabrams@outlook.com",
      phone: "+13135550013",
      type: "former_customer",
      status: "dormant",
      address: "5580 Cass Ave",
      city: "Detroit",
      state: "MI",
      zip: "48202",
      tags: ["hvac"],
      source: "google",
      lastServiceAt: ago(500 * DAY),
      lifetime_value: 2200,
      createdAt: ago(750 * DAY),
    },
    {
      id: "cnt_14",
      businessId: business.id,
      firstName: "Karen",
      lastName: "Whitfield",
      email: "kwhitfield@yahoo.com",
      phone: "+12485550014",
      type: "customer",
      status: "active",
      address: "1885 Catalpa Dr",
      city: "Berkley",
      state: "MI",
      zip: "48072",
      tags: ["furnace", "ac", "duct-cleaning"],
      source: "website",
      lastServiceAt: ago(70 * DAY),
      lifetime_value: 7100,
      createdAt: ago(650 * DAY),
    },
    {
      id: "cnt_15",
      businessId: business.id,
      firstName: "Steven",
      lastName: "Bakshi",
      email: "sbakshi@gmail.com",
      phone: "+15865550015",
      type: "lead",
      status: "active",
      address: "9200 Hall Rd",
      city: "Macomb",
      state: "MI",
      zip: "48044",
      tags: ["ac-install"],
      source: "google",
      notes: "Requested AC quote",
      lifetime_value: 0,
      createdAt: ago(5 * DAY),
    },
    {
      id: "cnt_16",
      businessId: business.id,
      firstName: "Nancy",
      lastName: "Kowalczyk",
      email: "nkowalczyk@comcast.net",
      phone: "+12485550016",
      type: "customer",
      status: "active",
      address: "775 Torquay Ave",
      city: "Royal Oak",
      state: "MI",
      zip: "48073",
      tags: ["plumbing", "sump-pump"],
      source: "referral",
      lastServiceAt: ago(35 * DAY),
      lifetime_value: 3200,
      createdAt: ago(400 * DAY),
    },
    {
      id: "cnt_17",
      businessId: business.id,
      firstName: "Brian",
      lastName: "Henderson",
      email: "bhenderson@gmail.com",
      phone: "+13135550017",
      type: "former_customer",
      status: "dormant",
      address: "2210 W Grand Blvd",
      city: "Detroit",
      state: "MI",
      zip: "48208",
      tags: ["furnace"],
      source: "google",
      lastServiceAt: ago(450 * DAY),
      lifetime_value: 1600,
      createdAt: ago(700 * DAY),
    },
    {
      id: "cnt_18",
      businessId: business.id,
      firstName: "Emily",
      lastName: "Larson",
      email: "elarson@gmail.com",
      phone: "+12485550018",
      type: "customer",
      status: "active",
      address: "340 Coolidge Hwy",
      city: "Pleasant Ridge",
      state: "MI",
      zip: "48069",
      tags: ["ac", "furnace"],
      source: "website",
      lastServiceAt: ago(120 * DAY),
      lifetime_value: 5900,
      notes: "Full system installed 2023",
      createdAt: ago(500 * DAY),
    },
    {
      id: "cnt_19",
      businessId: business.id,
      firstName: "Thomas",
      lastName: "Jankowski",
      phone: "+15865550019",
      type: "lead",
      status: "active",
      address: "4400 Garfield Rd",
      city: "Clinton Township",
      state: "MI",
      zip: "48038",
      tags: ["plumbing"],
      source: "missed_call",
      lifetime_value: 0,
      createdAt: ago(0.5 * DAY),
    },
    {
      id: "cnt_20",
      businessId: business.id,
      firstName: "Rachel",
      lastName: "Steinberg",
      email: "rsteinberg@gmail.com",
      phone: "+12485550020",
      type: "customer",
      status: "active",
      address: "1560 Southfield Rd",
      city: "Birmingham",
      state: "MI",
      zip: "48009",
      tags: ["maintenance-plan", "furnace", "ac"],
      source: "referral",
      lastServiceAt: ago(25 * DAY),
      lifetime_value: 9200,
      notes: "VIP customer",
      createdAt: ago(850 * DAY),
    },
    {
      id: "cnt_21",
      businessId: business.id,
      firstName: "Mark",
      lastName: "Alvarez",
      email: "malvarez@outlook.com",
      phone: "+13135550021",
      type: "customer",
      status: "active",
      address: "3750 Fort St",
      city: "Lincoln Park",
      state: "MI",
      zip: "48146",
      tags: ["furnace-repair"],
      source: "google",
      lastServiceAt: ago(150 * DAY),
      lifetime_value: 1900,
      createdAt: ago(350 * DAY),
    },
    {
      id: "cnt_22",
      businessId: business.id,
      firstName: "Diane",
      lastName: "Crawford",
      email: "dcrawford@yahoo.com",
      phone: "+12485550022",
      type: "former_customer",
      status: "dormant",
      address: "880 E Fourth St",
      city: "Royal Oak",
      state: "MI",
      zip: "48067",
      tags: ["plumbing", "water-heater"],
      source: "website",
      lastServiceAt: ago(365 * DAY),
      lifetime_value: 3400,
      notes: "Water heater may be due for replacement",
      createdAt: ago(600 * DAY),
    },
  ];

  for (const data of contactsData) {
    await prisma.contact.create({ data });
  }
  console.log(`  ✓ Contacts: ${contactsData.length}\n`);

  // ── Opportunities ───────────────────────────────────────
  console.log("  Creating opportunities...");
  const opportunitiesData: Parameters<typeof prisma.opportunity.create>[0]["data"][] = [
    {
      id: "opp_1",
      businessId: business.id,
      contactId: "cnt_7",
      assignedToId: "usr_3",
      type: "missed_call",
      status: "new",
      title: "Missed call - furnace not heating",
      description: "Customer called about furnace issues, after-hours call missed",
      estimatedValue: 450,
      serviceType: "Furnace Repair",
      priority: 2,
      source: "phone",
      attribution: "direct",
      createdAt: ago(1 * DAY),
    },
    {
      id: "opp_2",
      businessId: business.id,
      contactId: "cnt_4",
      assignedToId: "usr_2",
      type: "missed_call",
      status: "attempted",
      title: "Missed call - AC installation inquiry",
      description: "Potential new AC install, SMS follow-up sent",
      estimatedValue: 5500,
      serviceType: "AC Installation",
      priority: 3,
      source: "phone",
      attribution: "direct",
      createdAt: ago(3 * DAY),
    },
    {
      id: "opp_3",
      businessId: business.id,
      contactId: "cnt_11",
      assignedToId: "usr_3",
      type: "missed_call",
      status: "responded",
      title: "Missed call - water heater leaking",
      description: "Emergency water heater issue, customer responded to follow-up SMS",
      estimatedValue: 1800,
      serviceType: "Water Heater Replacement",
      priority: 3,
      source: "phone",
      attribution: "direct",
      createdAt: ago(2 * DAY),
    },
    {
      id: "opp_4",
      businessId: business.id,
      contactId: "cnt_19",
      type: "missed_call",
      status: "new",
      title: "Missed call - plumbing emergency",
      description: "After-hours call, no voicemail left",
      estimatedValue: 350,
      serviceType: "Plumbing Repair",
      priority: 1,
      source: "phone",
      attribution: "direct",
      createdAt: ago(0.5 * DAY),
    },
    {
      id: "opp_5",
      businessId: business.id,
      contactId: "cnt_15",
      assignedToId: "usr_2",
      type: "estimate_rescue",
      status: "attempted",
      title: "Stale estimate - AC replacement",
      description: "Estimate sent 12 days ago, no response. Follow-up SMS sent.",
      estimatedValue: 6200,
      serviceType: "AC Installation",
      priority: 3,
      source: "estimate",
      attribution: "direct",
      createdAt: ago(5 * DAY),
    },
    {
      id: "opp_6",
      businessId: business.id,
      contactId: "cnt_1",
      assignedToId: "usr_1",
      type: "estimate_rescue",
      status: "booked",
      title: "Stale estimate - furnace tune-up",
      description: "Customer re-engaged after follow-up, booked service",
      estimatedValue: 250,
      actualValue: 250,
      serviceType: "Furnace Maintenance",
      priority: 1,
      source: "estimate",
      attribution: "direct",
      resolvedAt: ago(1 * DAY),
      createdAt: ago(10 * DAY),
    },
    {
      id: "opp_7",
      businessId: business.id,
      contactId: "cnt_6",
      assignedToId: "usr_2",
      type: "estimate_rescue",
      status: "qualified",
      title: "Stale estimate - bathroom remodel plumbing",
      description: "Customer interested, requested updated pricing",
      estimatedValue: 8500,
      serviceType: "Plumbing Remodel",
      priority: 3,
      source: "estimate",
      attribution: "direct",
      createdAt: ago(8 * DAY),
    },
    {
      id: "opp_8",
      businessId: business.id,
      contactId: "cnt_10",
      assignedToId: "usr_3",
      type: "estimate_rescue",
      status: "lost",
      title: "Stale estimate - AC repair",
      description: "Customer went with another company",
      estimatedValue: 1200,
      serviceType: "AC Repair",
      priority: 1,
      source: "estimate",
      attribution: "direct",
      resolvedAt: ago(2 * DAY),
      createdAt: ago(14 * DAY),
    },
    {
      id: "opp_9",
      businessId: business.id,
      contactId: "cnt_3",
      assignedToId: "usr_2",
      type: "reactivation",
      status: "attempted",
      title: "Reactivation - annual maintenance",
      description: "No service in 12+ months, reactivation SMS sent",
      estimatedValue: 200,
      serviceType: "Annual Maintenance",
      priority: 1,
      source: "campaign",
      attribution: "influenced",
      createdAt: ago(7 * DAY),
    },
    {
      id: "opp_10",
      businessId: business.id,
      contactId: "cnt_8",
      assignedToId: "usr_1",
      type: "reactivation",
      status: "responded",
      title: "Reactivation - new home HVAC setup",
      description: "Former customer moved, interested in full system install",
      estimatedValue: 7500,
      serviceType: "HVAC Installation",
      priority: 3,
      source: "campaign",
      attribution: "influenced",
      createdAt: ago(6 * DAY),
    },
    {
      id: "opp_11",
      businessId: business.id,
      contactId: "cnt_13",
      assignedToId: "usr_3",
      type: "reactivation",
      status: "booked",
      title: "Reactivation - furnace inspection",
      description: "Dormant customer re-engaged, booked inspection",
      estimatedValue: 150,
      actualValue: 150,
      serviceType: "Furnace Inspection",
      priority: 1,
      source: "campaign",
      attribution: "influenced",
      resolvedAt: ago(2 * DAY),
      createdAt: ago(9 * DAY),
    },
    {
      id: "opp_12",
      businessId: business.id,
      contactId: "cnt_17",
      type: "reactivation",
      status: "new",
      title: "Reactivation - heating system checkup",
      description: "No service in 15+ months, eligible for reactivation",
      estimatedValue: 200,
      serviceType: "Heating Maintenance",
      priority: 1,
      source: "campaign",
      attribution: "influenced",
      createdAt: ago(4 * DAY),
    },
    {
      id: "opp_13",
      businessId: business.id,
      contactId: "cnt_22",
      assignedToId: "usr_2",
      type: "reactivation",
      status: "qualified",
      title: "Reactivation - water heater replacement",
      description: "Water heater is 10+ years old, customer interested in replacement",
      estimatedValue: 2800,
      serviceType: "Water Heater Replacement",
      priority: 2,
      source: "campaign",
      attribution: "influenced",
      createdAt: ago(5 * DAY),
    },
    {
      id: "opp_14",
      businessId: business.id,
      contactId: "cnt_2",
      assignedToId: "usr_1",
      type: "missed_call",
      status: "booked",
      title: "Missed call - drain clog",
      description: "Follow-up SMS led to booking for drain cleaning",
      estimatedValue: 300,
      actualValue: 350,
      serviceType: "Drain Cleaning",
      priority: 2,
      source: "phone",
      attribution: "direct",
      resolvedAt: ago(1 * DAY),
      createdAt: ago(4 * DAY),
    },
  ];

  for (const data of opportunitiesData) {
    await prisma.opportunity.create({ data });
  }
  console.log(`  ✓ Opportunities: ${opportunitiesData.length}\n`);

  // ── Call Events ─────────────────────────────────────────
  console.log("  Creating call events...");
  const callEventsData: Parameters<typeof prisma.callEvent.create>[0]["data"][] = [
    {
      id: "call_1",
      businessId: business.id,
      contactId: "cnt_7",
      opportunityId: "opp_1",
      callerNumber: "+15865559707",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: true,
      callStartedAt: ago(1 * DAY + 2 * HOUR),
      intakeSummary: "Furnace not heating - after hours missed call",
      createdAt: ago(1 * DAY + 2 * HOUR),
    },
    {
      id: "call_2",
      businessId: business.id,
      contactId: "cnt_4",
      opportunityId: "opp_2",
      callerNumber: "+12485559404",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: false,
      callStartedAt: ago(3 * DAY + 4 * HOUR),
      intakeSummary: "AC installation inquiry - call missed during lunch",
      createdAt: ago(3 * DAY + 4 * HOUR),
    },
    {
      id: "call_3",
      businessId: business.id,
      contactId: "cnt_11",
      opportunityId: "opp_3",
      callerNumber: "+15865550011",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: true,
      callStartedAt: ago(2 * DAY + 6 * HOUR),
      intakeSummary: "Water heater leaking - emergency call after hours",
      createdAt: ago(2 * DAY + 6 * HOUR),
    },
    {
      id: "call_4",
      businessId: business.id,
      contactId: "cnt_19",
      opportunityId: "opp_4",
      callerNumber: "+15865550019",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: true,
      callStartedAt: ago(0.5 * DAY),
      createdAt: ago(0.5 * DAY),
    },
    {
      id: "call_5",
      businessId: business.id,
      contactId: "cnt_2",
      opportunityId: "opp_14",
      callerNumber: "+13135559202",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: false,
      callStartedAt: ago(4 * DAY + 3 * HOUR),
      intakeSummary: "Drain clog, needs service today if possible",
      createdAt: ago(4 * DAY + 3 * HOUR),
    },
    {
      id: "call_6",
      businessId: business.id,
      contactId: "cnt_1",
      callerNumber: "+12485559101",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "answered",
      duration: 185,
      isAfterHours: false,
      callStartedAt: ago(5 * DAY + 1 * HOUR),
      callEndedAt: ago(5 * DAY + 1 * HOUR - 185000),
      transcription: "Customer called about scheduling annual furnace tune-up. Booked for next week.",
      intakeSummary: "Annual maintenance scheduling",
      createdAt: ago(5 * DAY + 1 * HOUR),
    },
    {
      id: "call_7",
      businessId: business.id,
      contactId: "cnt_6",
      callerNumber: "+13135559606",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "answered",
      duration: 420,
      isAfterHours: false,
      callStartedAt: ago(3 * DAY + 5 * HOUR),
      callEndedAt: ago(3 * DAY + 5 * HOUR - 420000),
      transcription: "Discussion about bathroom remodel plumbing scope and updated pricing.",
      intakeSummary: "Bathroom remodel follow-up discussion",
      createdAt: ago(3 * DAY + 5 * HOUR),
    },
    {
      id: "call_8",
      businessId: business.id,
      contactId: "cnt_20",
      callerNumber: "+12485550020",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "answered",
      duration: 95,
      isAfterHours: false,
      callStartedAt: ago(2 * DAY + 3 * HOUR),
      callEndedAt: ago(2 * DAY + 3 * HOUR - 95000),
      intakeSummary: "VIP customer checking on maintenance plan renewal",
      createdAt: ago(2 * DAY + 3 * HOUR),
    },
    {
      id: "call_9",
      businessId: business.id,
      contactId: "cnt_9",
      callerNumber: "+13135559909",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "answered",
      duration: 210,
      isAfterHours: false,
      callStartedAt: ago(6 * DAY + 2 * HOUR),
      callEndedAt: ago(6 * DAY + 2 * HOUR - 210000),
      transcription: "Customer inquiring about drain cleaning service options and pricing.",
      intakeSummary: "Drain cleaning inquiry",
      createdAt: ago(6 * DAY + 2 * HOUR),
    },
    {
      id: "call_10",
      businessId: business.id,
      callerNumber: "+12485550099",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "missed",
      isAfterHours: false,
      callStartedAt: ago(0.25 * DAY),
      createdAt: ago(0.25 * DAY),
    },
    {
      id: "call_11",
      businessId: business.id,
      contactId: "cnt_14",
      callerNumber: "+12485550014",
      calledNumber: "+12485551000",
      direction: "inbound",
      status: "answered",
      duration: 310,
      isAfterHours: false,
      callStartedAt: ago(1 * DAY + 4 * HOUR),
      callEndedAt: ago(1 * DAY + 4 * HOUR - 310000),
      transcription: "Customer scheduling duct cleaning and discussing HVAC filter options.",
      intakeSummary: "Duct cleaning scheduling and filter inquiry",
      createdAt: ago(1 * DAY + 4 * HOUR),
    },
  ];

  for (const data of callEventsData) {
    await prisma.callEvent.create({ data });
  }
  console.log(`  ✓ Call Events: ${callEventsData.length}\n`);

  // ── Estimates ───────────────────────────────────────────
  console.log("  Creating estimates...");
  const estimatesData: Parameters<typeof prisma.estimate.create>[0]["data"][] = [
    {
      id: "est_1",
      businessId: business.id,
      contactId: "cnt_15",
      opportunityId: "opp_5",
      externalId: "EST-1042",
      title: "Central AC Replacement - 3 Ton",
      amount: 6200,
      status: "stale",
      serviceType: "AC Installation",
      sentAt: ago(14 * DAY),
      followUpAt: ago(4 * DAY),
      expiresAt: future(16 * DAY),
      staleSince: ago(7 * DAY),
      createdAt: ago(14 * DAY),
    },
    {
      id: "est_2",
      businessId: business.id,
      contactId: "cnt_1",
      opportunityId: "opp_6",
      externalId: "EST-1038",
      title: "Furnace Annual Tune-Up",
      amount: 250,
      status: "booked",
      serviceType: "Furnace Maintenance",
      sentAt: ago(12 * DAY),
      followUpAt: ago(5 * DAY),
      staleSince: ago(5 * DAY),
      respondedAt: ago(3 * DAY),
      bookedAt: ago(1 * DAY),
      createdAt: ago(12 * DAY),
    },
    {
      id: "est_3",
      businessId: business.id,
      contactId: "cnt_6",
      opportunityId: "opp_7",
      externalId: "EST-1035",
      title: "Bathroom Remodel Plumbing Package",
      amount: 8500,
      status: "responded",
      serviceType: "Plumbing Remodel",
      sentAt: ago(18 * DAY),
      followUpAt: ago(8 * DAY),
      expiresAt: future(12 * DAY),
      staleSince: ago(11 * DAY),
      respondedAt: ago(3 * DAY),
      createdAt: ago(18 * DAY),
    },
    {
      id: "est_4",
      businessId: business.id,
      contactId: "cnt_10",
      opportunityId: "opp_8",
      externalId: "EST-1030",
      title: "AC Compressor Repair",
      amount: 1200,
      status: "lost",
      serviceType: "AC Repair",
      sentAt: ago(21 * DAY),
      followUpAt: ago(14 * DAY),
      expiresAt: ago(1 * DAY),
      staleSince: ago(14 * DAY),
      lostAt: ago(2 * DAY),
      lostReason: "Went with competitor - lower price",
      createdAt: ago(21 * DAY),
    },
    {
      id: "est_5",
      businessId: business.id,
      contactId: "cnt_9",
      externalId: "EST-1045",
      title: "Main Line Drain Cleaning",
      amount: 450,
      status: "open",
      serviceType: "Drain Cleaning",
      sentAt: ago(3 * DAY),
      expiresAt: future(27 * DAY),
      createdAt: ago(3 * DAY),
    },
    {
      id: "est_6",
      businessId: business.id,
      contactId: "cnt_14",
      externalId: "EST-1044",
      title: "Whole-Home Duct Cleaning",
      amount: 550,
      status: "open",
      serviceType: "Duct Cleaning",
      sentAt: ago(4 * DAY),
      expiresAt: future(26 * DAY),
      createdAt: ago(4 * DAY),
    },
    {
      id: "est_7",
      businessId: business.id,
      contactId: "cnt_22",
      opportunityId: "opp_13",
      externalId: "EST-1025",
      title: "50-Gallon Water Heater Installation",
      amount: 2800,
      status: "stale",
      serviceType: "Water Heater Replacement",
      sentAt: ago(20 * DAY),
      followUpAt: ago(10 * DAY),
      expiresAt: future(10 * DAY),
      staleSince: ago(13 * DAY),
      createdAt: ago(20 * DAY),
    },
    {
      id: "est_8",
      businessId: business.id,
      contactId: "cnt_5",
      externalId: "EST-1046",
      title: "Dual-Zone Thermostat Upgrade",
      amount: 850,
      status: "open",
      serviceType: "Thermostat Installation",
      sentAt: ago(2 * DAY),
      expiresAt: future(28 * DAY),
      createdAt: ago(2 * DAY),
    },
    {
      id: "est_9",
      businessId: business.id,
      contactId: "cnt_16",
      externalId: "EST-1040",
      title: "Sump Pump Replacement",
      amount: 1100,
      status: "booked",
      serviceType: "Sump Pump",
      sentAt: ago(10 * DAY),
      respondedAt: ago(7 * DAY),
      bookedAt: ago(5 * DAY),
      createdAt: ago(10 * DAY),
    },
    {
      id: "est_10",
      businessId: business.id,
      contactId: "cnt_12",
      externalId: "EST-1032",
      title: "Furnace Replacement - 80K BTU",
      amount: 4800,
      status: "stale",
      serviceType: "Furnace Replacement",
      sentAt: ago(16 * DAY),
      followUpAt: ago(9 * DAY),
      expiresAt: future(14 * DAY),
      staleSince: ago(9 * DAY),
      createdAt: ago(16 * DAY),
    },
    {
      id: "est_11",
      businessId: business.id,
      contactId: "cnt_21",
      externalId: "EST-1047",
      title: "Gas Line Repair",
      amount: 380,
      status: "open",
      serviceType: "Gas Line Repair",
      sentAt: ago(1 * DAY),
      expiresAt: future(29 * DAY),
      createdAt: ago(1 * DAY),
    },
  ];

  for (const data of estimatesData) {
    await prisma.estimate.create({ data });
  }
  console.log(`  ✓ Estimates: ${estimatesData.length}\n`);

  // ── Templates ───────────────────────────────────────────
  console.log("  Creating templates...");
  const templatesData: Parameters<typeof prisma.template.create>[0]["data"][] = [
    {
      id: "tpl_1",
      businessId: business.id,
      name: "Missed Call SMS",
      category: "missed_call",
      channel: "sms",
      body: "Hi {{firstName}}, this is {{businessName}}. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
      variables: ["firstName", "businessName"],
      createdAt: ago(90 * DAY),
    },
    {
      id: "tpl_2",
      businessId: business.id,
      name: "Estimate Follow-up SMS",
      category: "estimate_rescue",
      channel: "sms",
      body: "Hi {{firstName}}, your estimate for {{serviceType}} ({{estimateAmount}}) from {{businessName}} is still available. Any questions? We're happy to help!",
      variables: ["firstName", "serviceType", "estimateAmount", "businessName"],
      createdAt: ago(90 * DAY),
    },
    {
      id: "tpl_3",
      businessId: business.id,
      name: "Reactivation SMS",
      category: "reactivation",
      channel: "sms",
      body: "Hi {{firstName}}, it's been a while since your last visit with {{businessName}}! We'd love to help keep your home comfortable. Reply BOOK to schedule a service.",
      variables: ["firstName", "businessName"],
      createdAt: ago(90 * DAY),
    },
    {
      id: "tpl_4",
      businessId: business.id,
      name: "Appointment Confirmation",
      category: "booking",
      channel: "sms",
      body: "Hi {{firstName}}, your appointment with {{businessName}} is confirmed for {{appointmentDate}} at {{appointmentTime}}. Reply C to confirm or R to reschedule.",
      variables: ["firstName", "businessName", "appointmentDate", "appointmentTime"],
      createdAt: ago(90 * DAY),
    },
    {
      id: "tpl_5",
      businessId: business.id,
      name: "Seasonal Maintenance Email",
      category: "reactivation",
      channel: "email",
      subject: "Time for your seasonal maintenance checkup!",
      body: "Dear {{firstName}},\n\nIt's that time of year again! {{businessName}} is offering seasonal maintenance specials to keep your home running smoothly.\n\nAs a valued customer, we'd like to offer you priority scheduling. Your last service was {{lastServiceDate}} - staying on top of maintenance helps prevent costly repairs.\n\nSpecial offer: Book your tune-up this month and save {{discountAmount}}!\n\nCall us at (248) 555-1000 or reply to schedule.\n\nBest regards,\nThe {{businessName}} Team",
      variables: ["firstName", "businessName", "lastServiceDate", "discountAmount"],
      createdAt: ago(60 * DAY),
    },
  ];

  for (const data of templatesData) {
    await prisma.template.create({ data });
  }
  console.log(`  ✓ Templates: ${templatesData.length}\n`);

  // ── Campaigns with Steps ────────────────────────────────
  console.log("  Creating campaigns...");
  await prisma.campaign.create({
    data: {
      id: "cmp_1",
      businessId: business.id,
      name: "Winter Missed Call Recovery",
      type: "missed_call_followup",
      status: "active",
      channel: "sms",
      targetSegment: "Missed calls - last 30 days",
      targetCount: 45,
      sentCount: 38,
      respondedCount: 16,
      bookedCount: 9,
      revenue: 14200,
      startAt: ago(21 * DAY),
      stopOnReply: true,
      stopOnBooking: true,
      createdAt: ago(22 * DAY),
      steps: {
        create: [
          {
            id: "step_1",
            stepOrder: 1,
            channel: "sms",
            templateId: "tpl_1",
            delayMinutes: 5,
            body: "Hi {{firstName}}, this is {{businessName}}. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
            createdAt: ago(22 * DAY),
          },
          {
            id: "step_2",
            stepOrder: 2,
            channel: "sms",
            delayMinutes: 1440,
            body: "Hi {{firstName}}, just following up from {{businessName}}. We'd love to help with your heating or plumbing needs. Reply BOOK to schedule.",
            createdAt: ago(22 * DAY),
          },
        ],
      },
    },
  });

  await prisma.campaign.create({
    data: {
      id: "cmp_2",
      businessId: business.id,
      name: "Q1 Estimate Follow-up",
      type: "estimate_rescue",
      status: "active",
      channel: "sms",
      targetSegment: "Stale estimates - 7+ days",
      targetCount: 28,
      sentCount: 24,
      respondedCount: 8,
      bookedCount: 4,
      revenue: 18500,
      startAt: ago(30 * DAY),
      stopOnReply: true,
      stopOnBooking: true,
      createdAt: ago(31 * DAY),
      steps: {
        create: [
          {
            id: "step_3",
            stepOrder: 1,
            channel: "sms",
            templateId: "tpl_2",
            delayMinutes: 0,
            body: "Hi {{firstName}}, your estimate for {{serviceType}} ({{estimateAmount}}) from {{businessName}} is still available. Any questions? We're happy to help!",
            createdAt: ago(31 * DAY),
          },
          {
            id: "step_4",
            stepOrder: 2,
            channel: "sms",
            delayMinutes: 4320,
            body: "Hi {{firstName}}, just a reminder - your {{serviceType}} estimate expires soon. Reply YES to lock in your price or call (248) 555-1000.",
            createdAt: ago(31 * DAY),
          },
        ],
      },
    },
  });

  await prisma.campaign.create({
    data: {
      id: "cmp_3",
      businessId: business.id,
      name: "Spring Maintenance Reactivation",
      type: "reactivation",
      status: "completed",
      channel: "sms",
      targetSegment: "No service in 12+ months",
      targetCount: 62,
      sentCount: 62,
      respondedCount: 19,
      bookedCount: 11,
      revenue: 24800,
      startAt: ago(60 * DAY),
      endAt: ago(30 * DAY),
      stopOnReply: true,
      stopOnBooking: true,
      createdAt: ago(65 * DAY),
      steps: {
        create: [
          {
            id: "step_5",
            stepOrder: 1,
            channel: "sms",
            templateId: "tpl_3",
            delayMinutes: 0,
            body: "Hi {{firstName}}, it's been a while! {{businessName}} is running a spring maintenance special. Schedule your AC tune-up for just $149. Reply BOOK!",
            createdAt: ago(65 * DAY),
          },
        ],
      },
    },
  });

  await prisma.campaign.create({
    data: {
      id: "cmp_4",
      businessId: business.id,
      name: "Emergency HVAC Follow-up",
      type: "missed_call_followup",
      status: "draft",
      channel: "sms",
      targetSegment: "After-hours missed calls",
      targetCount: 0,
      sentCount: 0,
      respondedCount: 0,
      bookedCount: 0,
      revenue: 0,
      stopOnReply: true,
      stopOnBooking: true,
      createdAt: ago(2 * DAY),
      steps: {
        create: [
          {
            id: "step_6",
            stepOrder: 1,
            channel: "sms",
            templateId: "tpl_1",
            delayMinutes: 0,
            body: "Hi {{firstName}}, we see you tried to reach {{businessName}} after hours. We're now open! How can we help? Call (248) 555-1000 or reply here.",
            createdAt: ago(2 * DAY),
          },
        ],
      },
    },
  });
  console.log("  ✓ Campaigns: 4 (with steps)\n");

  // ── Message Events ──────────────────────────────────────
  console.log("  Creating message events...");
  const messageEventsData: Parameters<typeof prisma.messageEvent.create>[0]["data"][] = [
    {
      id: "msg_1",
      businessId: business.id,
      contactId: "cnt_7",
      opportunityId: "opp_1",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+15865559707",
      body: "Hi David, this is North Shore Heating & Plumbing. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
      sentAt: ago(1 * DAY + 1 * HOUR),
      deliveredAt: ago(1 * DAY + 1 * HOUR - 30000),
      createdAt: ago(1 * DAY + 1 * HOUR),
    },
    {
      id: "msg_2",
      businessId: business.id,
      contactId: "cnt_4",
      opportunityId: "opp_2",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+12485559404",
      body: "Hi Lisa, this is North Shore Heating & Plumbing. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
      sentAt: ago(2.5 * DAY),
      deliveredAt: ago(2.5 * DAY - 15000),
      createdAt: ago(2.5 * DAY),
    },
    {
      id: "msg_3",
      businessId: business.id,
      contactId: "cnt_11",
      opportunityId: "opp_3",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+15865550011",
      body: "Hi William, this is North Shore Heating & Plumbing. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
      sentAt: ago(2 * DAY + 5 * HOUR),
      deliveredAt: ago(2 * DAY + 5 * HOUR - 20000),
      createdAt: ago(2 * DAY + 5 * HOUR),
    },
    {
      id: "msg_4",
      businessId: business.id,
      contactId: "cnt_11",
      opportunityId: "opp_3",
      channel: "sms",
      direction: "inbound",
      status: "replied",
      fromNumber: "+15865550011",
      toNumber: "+12485551000",
      body: "Yes, I need help with my water heater. It's leaking badly.",
      repliedAt: ago(1.5 * DAY),
      createdAt: ago(1.5 * DAY),
    },
    {
      id: "msg_5",
      businessId: business.id,
      contactId: "cnt_19",
      opportunityId: "opp_4",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+15865550019",
      body: "Hi Thomas, we see you tried to reach North Shore Heating & Plumbing after hours. We're now open! How can we help? Call (248) 555-1000 or reply here.",
      sentAt: ago(0.25 * DAY),
      deliveredAt: ago(0.25 * DAY - 10000),
      createdAt: ago(0.25 * DAY),
    },
    {
      id: "msg_6",
      businessId: business.id,
      contactId: "cnt_15",
      opportunityId: "opp_5",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+15865550015",
      body: "Hi Steven, your estimate for AC Installation ($6,200) from North Shore Heating & Plumbing is still available. Any questions? We're happy to help!",
      sentAt: ago(4 * DAY),
      deliveredAt: ago(4 * DAY - 25000),
      createdAt: ago(4 * DAY),
    },
    {
      id: "msg_7",
      businessId: business.id,
      contactId: "cnt_2",
      opportunityId: "opp_14",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+13135559202",
      body: "Hi Maria, this is North Shore Heating & Plumbing. We noticed we missed your call. How can we help? Reply or call us at (248) 555-1000.",
      sentAt: ago(4 * DAY + 2 * HOUR),
      deliveredAt: ago(4 * DAY + 2 * HOUR - 20000),
      createdAt: ago(4 * DAY + 2 * HOUR),
    },
    {
      id: "msg_8",
      businessId: business.id,
      contactId: "cnt_2",
      opportunityId: "opp_14",
      channel: "sms",
      direction: "inbound",
      status: "replied",
      fromNumber: "+13135559202",
      toNumber: "+12485551000",
      body: "Hi yes, I have a drain clog. Can someone come out today?",
      repliedAt: ago(4 * DAY + 1 * HOUR),
      createdAt: ago(4 * DAY + 1 * HOUR),
    },
    {
      id: "msg_9",
      businessId: business.id,
      contactId: "cnt_3",
      opportunityId: "opp_9",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+15865559303",
      body: "Hi Robert, it's been a while since your last visit with North Shore Heating & Plumbing! We'd love to help keep your home comfortable. Reply BOOK to schedule a service.",
      sentAt: ago(6 * DAY),
      deliveredAt: ago(6 * DAY - 30000),
      createdAt: ago(6 * DAY),
    },
    {
      id: "msg_10",
      businessId: business.id,
      contactId: "cnt_8",
      opportunityId: "opp_10",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+12485559808",
      body: "Hi Patricia, it's been a while since your last visit with North Shore Heating & Plumbing! We'd love to help keep your home comfortable. Reply BOOK to schedule a service.",
      sentAt: ago(6 * DAY),
      deliveredAt: ago(6 * DAY - 15000),
      createdAt: ago(6 * DAY),
    },
    {
      id: "msg_11",
      businessId: business.id,
      contactId: "cnt_8",
      opportunityId: "opp_10",
      channel: "sms",
      direction: "inbound",
      status: "replied",
      fromNumber: "+12485559808",
      toNumber: "+12485551000",
      body: "Yes, we need a quote for our new home. We moved to a new house and need full HVAC.",
      repliedAt: ago(4 * DAY),
      createdAt: ago(4 * DAY),
    },
    {
      id: "msg_12",
      businessId: business.id,
      contactId: "cnt_13",
      opportunityId: "opp_11",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+13135550013",
      body: "Hi Daniel, it's been a while! North Shore Heating & Plumbing is running a spring maintenance special. Schedule your furnace inspection for just $149. Reply BOOK!",
      sentAt: ago(9 * DAY),
      deliveredAt: ago(9 * DAY - 20000),
      createdAt: ago(9 * DAY),
    },
    {
      id: "msg_13",
      businessId: business.id,
      contactId: "cnt_13",
      opportunityId: "opp_11",
      channel: "sms",
      direction: "inbound",
      status: "replied",
      fromNumber: "+13135550013",
      toNumber: "+12485551000",
      body: "BOOK - I'd like to schedule a furnace inspection please.",
      repliedAt: ago(8 * DAY),
      createdAt: ago(8 * DAY),
    },
    {
      id: "msg_14",
      businessId: business.id,
      contactId: "cnt_22",
      opportunityId: "opp_13",
      channel: "sms",
      direction: "outbound",
      status: "delivered",
      fromNumber: "+12485551000",
      toNumber: "+12485550022",
      body: "Hi Diane, it's been a while since your last visit with North Shore Heating & Plumbing! We'd love to help keep your home comfortable. Reply BOOK to schedule a service.",
      sentAt: ago(5 * DAY),
      deliveredAt: ago(5 * DAY - 10000),
      createdAt: ago(5 * DAY),
    },
  ];

  for (const data of messageEventsData) {
    await prisma.messageEvent.create({ data });
  }
  console.log(`  ✓ Message Events: ${messageEventsData.length}\n`);

  // ── Bookings ────────────────────────────────────────────
  console.log("  Creating bookings...");
  const bookingsData: Parameters<typeof prisma.booking.create>[0]["data"][] = [
    {
      id: "bk_1",
      businessId: business.id,
      contactId: "cnt_1",
      opportunityId: "opp_6",
      userId: "usr_1",
      title: "Furnace Annual Tune-Up",
      serviceType: "Furnace Maintenance",
      scheduledAt: future(3 * DAY),
      amount: 250,
      source: "estimate_rescue",
      attribution: "direct",
      notes: "Annual maintenance plan customer",
      createdAt: ago(1 * DAY),
    },
    {
      id: "bk_2",
      businessId: business.id,
      contactId: "cnt_2",
      opportunityId: "opp_14",
      userId: "usr_3",
      title: "Drain Cleaning Service",
      serviceType: "Drain Cleaning",
      scheduledAt: future(1 * DAY),
      amount: 350,
      source: "missed_call",
      attribution: "direct",
      notes: "Follow-up from missed call recovery",
      createdAt: ago(1 * DAY),
    },
    {
      id: "bk_3",
      businessId: business.id,
      contactId: "cnt_13",
      opportunityId: "opp_11",
      userId: "usr_3",
      title: "Furnace Inspection",
      serviceType: "Furnace Inspection",
      scheduledAt: future(5 * DAY),
      amount: 150,
      source: "reactivation",
      attribution: "influenced",
      notes: "Reactivated dormant customer",
      createdAt: ago(2 * DAY),
    },
    {
      id: "bk_4",
      businessId: business.id,
      contactId: "cnt_16",
      userId: "usr_2",
      title: "Sump Pump Replacement",
      serviceType: "Sump Pump",
      scheduledAt: future(2 * DAY),
      amount: 1100,
      source: "manual",
      attribution: "direct",
      createdAt: ago(5 * DAY),
    },
    {
      id: "bk_5",
      businessId: business.id,
      contactId: "cnt_20",
      userId: "usr_1",
      title: "Maintenance Plan Renewal - Full System",
      serviceType: "Maintenance Plan",
      scheduledAt: future(7 * DAY),
      amount: 450,
      source: "manual",
      attribution: "direct",
      notes: "VIP customer annual renewal",
      createdAt: ago(2 * DAY),
    },
    {
      id: "bk_6",
      businessId: business.id,
      contactId: "cnt_5",
      userId: "usr_2",
      title: "Thermostat Upgrade - Dual Zone",
      serviceType: "Thermostat Installation",
      scheduledAt: future(4 * DAY),
      amount: 850,
      source: "manual",
      attribution: "direct",
      notes: "Upgrading to smart thermostat",
      createdAt: ago(1.5 * DAY),
    },
    {
      id: "bk_7",
      businessId: business.id,
      contactId: "cnt_9",
      userId: "usr_3",
      title: "Kitchen Drain Cleaning",
      serviceType: "Drain Cleaning",
      scheduledAt: ago(3 * DAY),
      amount: 300,
      source: "missed_call",
      attribution: "direct",
      notes: "Completed",
      createdAt: ago(6 * DAY),
    },
    {
      id: "bk_8",
      businessId: business.id,
      contactId: "cnt_12",
      userId: "usr_1",
      title: "Furnace Diagnostic",
      serviceType: "Furnace Repair",
      scheduledAt: ago(5 * DAY),
      amount: 175,
      source: "reactivation",
      attribution: "influenced",
      notes: "Completed - recommended full replacement",
      createdAt: ago(8 * DAY),
    },
  ];

  for (const data of bookingsData) {
    await prisma.booking.create({ data });
  }
  console.log(`  ✓ Bookings: ${bookingsData.length}\n`);

  // ── Activity Logs ───────────────────────────────────────
  console.log("  Creating activity logs...");
  const activityLogsData: Parameters<typeof prisma.activityLog.create>[0]["data"][] = [
    {
      id: "act_1",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_4",
      action: "sms_sent",
      description: "SMS sent to Thomas Jankowski - missed call follow-up",
      createdAt: ago(0.25 * DAY),
    },
    {
      id: "act_2",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_4",
      action: "opportunity_created",
      description: "Opportunity created from missed call - Thomas Jankowski",
      createdAt: ago(0.5 * DAY),
    },
    {
      id: "act_3",
      businessId: business.id,
      userId: "usr_3",
      entityType: "booking",
      entityId: "bk_2",
      action: "booking_confirmed",
      description: "Booking confirmed for drain cleaning - Maria Gonzalez",
      createdAt: ago(1 * DAY),
    },
    {
      id: "act_4",
      businessId: business.id,
      userId: "usr_1",
      entityType: "opportunity",
      entityId: "opp_14",
      action: "status_change",
      description: "Opportunity 'Missed call - drain clog' moved to Booked",
      createdAt: ago(1 * DAY),
    },
    {
      id: "act_5",
      businessId: business.id,
      userId: "usr_1",
      entityType: "booking",
      entityId: "bk_1",
      action: "booking_confirmed",
      description: "Booking confirmed for furnace tune-up - John Kowalski",
      createdAt: ago(1 * DAY),
    },
    {
      id: "act_6",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_3",
      action: "sms_received",
      description: "SMS reply received from William Foster - 'Yes, I need help with my water heater'",
      createdAt: ago(1.5 * DAY),
    },
    {
      id: "act_7",
      businessId: business.id,
      entityType: "estimate",
      entityId: "est_1",
      action: "estimate_stale",
      description: "Estimate EST-1042 for AC replacement is now 14 days stale",
      createdAt: ago(2 * DAY),
    },
    {
      id: "act_8",
      businessId: business.id,
      userId: "usr_3",
      entityType: "booking",
      entityId: "bk_3",
      action: "booking_confirmed",
      description: "Booking confirmed for furnace inspection - Daniel Abrams",
      createdAt: ago(2 * DAY),
    },
    {
      id: "act_9",
      businessId: business.id,
      userId: "usr_2",
      entityType: "opportunity",
      entityId: "opp_8",
      action: "opportunity_lost",
      description: "Opportunity 'Stale estimate - AC repair' marked as Lost - competitor",
      createdAt: ago(2 * DAY),
    },
    {
      id: "act_10",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_1",
      action: "sms_sent",
      description: "SMS sent to David Kim - missed call recovery",
      createdAt: ago(1 * DAY + 1 * HOUR),
    },
    {
      id: "act_11",
      businessId: business.id,
      userId: "usr_1",
      entityType: "opportunity",
      entityId: "opp_10",
      action: "note_added",
      description: "Note added to opportunity - Patricia Murphy interested in full HVAC install",
      createdAt: ago(3 * DAY),
    },
    {
      id: "act_12",
      businessId: business.id,
      entityType: "campaign",
      entityId: "cmp_1",
      action: "campaign_started",
      description: "Campaign 'Winter Missed Call Recovery' sent 12 new messages",
      createdAt: ago(3 * DAY),
    },
    {
      id: "act_13",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_9",
      action: "sms_sent",
      description: "SMS sent to Robert Thompson - reactivation outreach",
      createdAt: ago(6 * DAY),
    },
    {
      id: "act_14",
      businessId: business.id,
      entityType: "contact",
      entityId: "cnt_7",
      action: "contact_created",
      description: "New contact created - David Kim (from missed call)",
      createdAt: ago(1 * DAY),
    },
    {
      id: "act_15",
      businessId: business.id,
      userId: "usr_2",
      entityType: "opportunity",
      entityId: "opp_7",
      action: "status_change",
      description: "Opportunity 'Stale estimate - bathroom remodel' moved to Qualified",
      createdAt: ago(3 * DAY),
    },
    {
      id: "act_16",
      businessId: business.id,
      entityType: "opportunity",
      entityId: "opp_10",
      action: "sms_received",
      description: "SMS reply received from Patricia Murphy - 'Yes, we need a quote for our new home'",
      createdAt: ago(4 * DAY),
    },
  ];

  for (const data of activityLogsData) {
    await prisma.activityLog.create({ data });
  }
  console.log(`  ✓ Activity Logs: ${activityLogsData.length}\n`);

  // ── Integration Connections ─────────────────────────────
  console.log("  Creating integration connections...");
  const integrationsData: Parameters<typeof prisma.integrationConnection.create>[0]["data"][] = [
    {
      businessId: business.id,
      provider: "twilio",
      status: "connected",
      lastSyncAt: ago(5 * 60 * 1000),
      config: { accountSid: "AC_demo", phoneNumber: "+12485551000" },
    },
    {
      businessId: business.id,
      provider: "gmail",
      status: "connected",
      lastSyncAt: ago(15 * 60 * 1000),
      config: { email: "info@northshoreheating.com" },
    },
    {
      businessId: business.id,
      provider: "google_calendar",
      status: "connected",
      lastSyncAt: ago(10 * 60 * 1000),
      config: { calendarId: "primary" },
    },
    {
      businessId: business.id,
      provider: "csv",
      status: "connected",
      lastSyncAt: ago(2 * DAY),
      config: { lastImport: "contacts_2024.csv" },
    },
    {
      businessId: business.id,
      provider: "jobber",
      status: "disconnected",
    },
    {
      businessId: business.id,
      provider: "housecall_pro",
      status: "disconnected",
    },
    {
      businessId: business.id,
      provider: "servicetitan",
      status: "disconnected",
    },
    {
      businessId: business.id,
      provider: "outlook",
      status: "disconnected",
    },
  ];

  for (const data of integrationsData) {
    await prisma.integrationConnection.create({ data });
  }
  console.log(`  ✓ Integrations: ${integrationsData.length}\n`);

  // ── Report Snapshots ────────────────────────────────────
  console.log("  Creating report snapshots...");
  await prisma.reportSnapshot.create({
    data: {
      id: "rpt_1",
      businessId: business.id,
      reportType: "weekly_summary",
      periodStart: ago(7 * DAY),
      periodEnd: new Date(),
      data: {
        totalRevenue: 32700,
        totalOpportunities: 18,
        totalBookings: 9,
        missedCallRecoveryRate: 0.42,
        estimateRescueRate: 0.33,
        reactivationRate: 0.31,
        avgResponseTimeMinutes: 4.2,
        topServiceType: "Furnace Repair",
      },
    },
  });

  await prisma.reportSnapshot.create({
    data: {
      id: "rpt_2",
      businessId: business.id,
      reportType: "monthly_summary",
      periodStart: ago(30 * DAY),
      periodEnd: new Date(),
      data: {
        totalRevenue: 127850,
        totalOpportunities: 67,
        totalBookings: 34,
        missedCallRecoveryRate: 0.38,
        estimateRescueRate: 0.29,
        reactivationRate: 0.27,
        avgResponseTimeMinutes: 5.1,
        topServiceType: "AC Installation",
      },
    },
  });
  console.log("  ✓ Report Snapshots: 2\n");

  console.log("🌱 Seed complete!\n");
  console.log("  Demo tenant: North Shore Heating & Plumbing");
  console.log("  Users:");
  console.log("    - mike@northshoreheating.com  (owner)");
  console.log("    - sarah@northshoreheating.com (manager)");
  console.log("    - jake@northshoreheating.com  (csr)");
  console.log("  Password: demo\n");
}

const prisma = new PrismaClient();
seed()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
