import type {
  DemoActivityLog,
  DemoAlert,
  DemoBooking,
  DemoBusiness,
  DemoCallEvent,
  DemoCampaign,
  DemoCampaignStep,
  DemoContact,
  DemoEstimate,
  DemoIntegrationConnection,
  DemoMessageEvent,
  DemoOpportunity,
  DemoOpportunityNote,
  DemoReportSnapshot,
  DemoTemplate,
  DemoTenantData,
  DemoUser,
} from "@/lib/domain/types";

const now = new Date("2026-03-18T13:30:00.000Z");

function isoDaysAgo(days: number, hour = 13, minute = 30) {
  const date = new Date(now);
  date.setUTCDate(date.getUTCDate() - days);
  date.setUTCHours(hour, minute, 0, 0);
  return date.toISOString();
}

function isoHoursAgo(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

function isoDaysFromNow(days: number, hour = 14, minute = 0) {
  const date = new Date(now);
  date.setUTCDate(date.getUTCDate() + days);
  date.setUTCHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const demoBusiness: DemoBusiness = {
  id: "biz_north_shore",
  name: "North Shore Heating & Plumbing",
  industry: "multi_trade",
  timezone: "America/Detroit",
  staleEstimateDays: 7,
  attributionWindowDays: 14,
  highValueThreshold: 2500,
  duplicateMissedCallSuppressionHours: 4,
};

export const demoUsers: DemoUser[] = [
  {
    id: "user_owner_sarah",
    businessId: demoBusiness.id,
    name: "Sarah Mitchell",
    email: "owner@northshore.demo",
    role: "owner",
    password: "DemoPass123!",
  },
  {
    id: "user_manager_chris",
    businessId: demoBusiness.id,
    name: "Chris Alvarez",
    email: "manager@northshore.demo",
    role: "manager",
    password: "DemoPass123!",
  },
  {
    id: "user_csr_jamie",
    businessId: demoBusiness.id,
    name: "Jamie Carter",
    email: "csr@northshore.demo",
    role: "csr",
    password: "DemoPass123!",
  },
];

export const demoLocations = [
  {
    id: "loc_main",
    businessId: demoBusiness.id,
    name: "Main Dispatch",
    phone: "(248) 555-0101",
    addressLine1: "42 Harbor View Dr",
    city: "Northville",
    state: "MI",
    postalCode: "48167",
    isPrimary: true,
  },
  {
    id: "loc_ann_arbor",
    businessId: demoBusiness.id,
    name: "Ann Arbor Service Hub",
    phone: "(734) 555-0144",
    addressLine1: "850 Jackson Ave",
    city: "Ann Arbor",
    state: "MI",
    postalCode: "48103",
    isPrimary: false,
  },
] as const;

const contactSeed = [
  ["contact_01", "Laura", "Jensen", "laura.jensen@example.com", "(248) 555-1001", "customer", "active", ["vip", "furnace"], 18],
  ["contact_02", "Mark", "Ellis", "mark.ellis@example.com", "(248) 555-1002", "lead", "active", ["after-hours"], 400],
  ["contact_03", "Patricia", "Gomez", "patricia.gomez@example.com", "(248) 555-1003", "former_customer", "dormant", ["reactivation"], 420],
  ["contact_04", "Allen", "Bishop", "allen.bishop@example.com", "(734) 555-1004", "customer", "active", ["plumbing"], 45],
  ["contact_05", "Denise", "Reed", "denise.reed@example.com", "(734) 555-1005", "lead", "active", ["estimate"], 10],
  ["contact_06", "Omar", "Patel", "omar.patel@example.com", "(248) 555-1006", "customer", "active", ["maintenance"], 365],
  ["contact_07", "Sharon", "Lucas", "sharon.lucas@example.com", "(248) 555-1007", "customer", "active", ["membership"], 335],
  ["contact_08", "Tyler", "Shaw", "tyler.shaw@example.com", "(734) 555-1008", "lead", "active", ["estimate"], 9],
  ["contact_09", "Rebecca", "Mills", "rebecca.mills@example.com", "(248) 555-1009", "former_customer", "dormant", ["replacement"], 780],
  ["contact_10", "George", "Cook", "george.cook@example.com", "(248) 555-1010", "customer", "active", ["water-heater"], 26],
  ["contact_11", "Amy", "Ford", "amy.ford@example.com", "(734) 555-1011", "lead", "active", ["missed-call"], 3],
  ["contact_12", "Vincent", "Hale", "vincent.hale@example.com", "(734) 555-1012", "customer", "active", ["electrical"], 60],
  ["contact_13", "Naomi", "Fisher", "naomi.fisher@example.com", "(248) 555-1013", "former_customer", "dormant", ["membership"], 560],
  ["contact_14", "Ben", "Garcia", "ben.garcia@example.com", "(248) 555-1014", "customer", "active", ["boiler"], 90],
  ["contact_15", "Aisha", "Turner", "aisha.turner@example.com", "(248) 555-1015", "lead", "active", ["after-hours"], 7],
  ["contact_16", "Connor", "Davis", "connor.davis@example.com", "(734) 555-1016", "lead", "active", ["estimate"], 12],
  ["contact_17", "Melanie", "Ross", "melanie.ross@example.com", "(248) 555-1017", "customer", "active", ["maintenance"], 390],
  ["contact_18", "Jason", "Nguyen", "jason.nguyen@example.com", "(248) 555-1018", "customer", "active", ["drain"], 120],
  ["contact_19", "Olivia", "Price", "olivia.price@example.com", "(734) 555-1019", "former_customer", "dormant", ["reactivation"], 510],
  ["contact_20", "Ethan", "Ward", "ethan.ward@example.com", "(248) 555-1020", "customer", "active", ["vip"], 32],
  ["contact_21", "Janet", "Brooks", "janet.brooks@example.com", "(248) 555-1021", "former_customer", "dormant", ["replacement"], 650],
  ["contact_22", "Leo", "Kim", "leo.kim@example.com", "(734) 555-1022", "lead", "active", ["electrical"], 14],
] as const;

export const demoContacts: DemoContact[] = contactSeed.map(
  ([id, firstName, lastName, email, phone, type, status, tags, daysSinceService], index) => ({
    id,
    businessId: demoBusiness.id,
    locationId: index % 3 === 0 ? "loc_ann_arbor" : "loc_main",
    firstName,
    lastName,
    email,
    phone,
    type,
    status,
    tags: [...tags],
    source: type === "lead" ? "Google Local Services" : "Existing customer base",
    notesSummary:
      status === "dormant"
        ? "Dormant household likely due for outreach."
        : "Responsive homeowner with recurring service history.",
    lastServiceAt: isoDaysAgo(daysSinceService),
    lastContactedAt: isoDaysAgo(Math.max(1, Math.floor(daysSinceService / 4))),
  }),
);

export const demoOpportunities: DemoOpportunity[] = [
  {
    id: "opp_missed_01",
    businessId: demoBusiness.id,
    contactId: "contact_11",
    locationId: "loc_ann_arbor",
    ownerId: "user_csr_jamie",
    type: "missed_call",
    status: "booked",
    title: "Same-day AC repair missed call",
    description: "Missed lunchtime inbound call for AC not cooling.",
    serviceType: "AC repair",
    value: 780,
    sourceLabel: "Google Ads",
    intakeSummary: "Homeowner asked for same-day diagnostic and quoted noisy outdoor unit.",
    lastContactAt: isoHoursAgo(2),
    bookedAt: isoDaysFromNow(1, 15, 0),
    createdAt: isoHoursAgo(6),
    updatedAt: isoHoursAgo(1),
  },
  {
    id: "opp_missed_02",
    businessId: demoBusiness.id,
    contactId: "contact_15",
    locationId: "loc_main",
    ownerId: "user_csr_jamie",
    type: "missed_call",
    status: "attempted",
    title: "After-hours furnace no-heat voicemail",
    description: "Caller left voicemail after 8pm requesting emergency heat repair.",
    serviceType: "Furnace repair",
    value: 950,
    sourceLabel: "Organic search",
    intakeSummary: "Voicemail mentions no heat and elderly parent in home.",
    nextActionAt: isoHoursAgo(-1),
    lastContactAt: isoHoursAgo(5),
    createdAt: isoHoursAgo(10),
    updatedAt: isoHoursAgo(5),
  },
  {
    id: "opp_missed_03",
    businessId: demoBusiness.id,
    contactId: "contact_02",
    locationId: "loc_main",
    ownerId: "user_manager_chris",
    type: "missed_call",
    status: "lost",
    title: "Weekend drain cleaning missed call",
    description: "Abandoned call during Saturday overflow.",
    serviceType: "Drain cleaning",
    value: 420,
    sourceLabel: "Google Business Profile",
    intakeSummary: "Caller hung up after 48 seconds in queue.",
    closedAt: isoDaysAgo(2),
    createdAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(2),
  },
  {
    id: "opp_missed_04",
    businessId: demoBusiness.id,
    contactId: "contact_20",
    locationId: "loc_main",
    ownerId: "user_csr_jamie",
    type: "missed_call",
    status: "responded",
    title: "Water heater quote callback needed",
    description: "Missed inbound call from returning VIP customer.",
    serviceType: "Water heater install",
    value: 3200,
    sourceLabel: "Direct",
    intakeSummary: "Customer wants options for 50-gallon gas replacement.",
    nextActionAt: isoDaysFromNow(1, 16, 0),
    lastContactAt: isoHoursAgo(3),
    createdAt: isoHoursAgo(8),
    updatedAt: isoHoursAgo(3),
  },
  {
    id: "opp_est_01",
    businessId: demoBusiness.id,
    contactId: "contact_05",
    locationId: "loc_ann_arbor",
    ownerId: "user_manager_chris",
    type: "estimate_rescue",
    status: "new",
    title: "Stale ductless mini-split proposal",
    description: "Estimate passed stale threshold without reply.",
    serviceType: "Mini-split install",
    value: 6400,
    sourceLabel: "Technician quote",
    nextActionAt: isoDaysFromNow(1),
    createdAt: isoDaysAgo(8),
    updatedAt: isoDaysAgo(8),
  },
  {
    id: "opp_est_02",
    businessId: demoBusiness.id,
    contactId: "contact_08",
    locationId: "loc_main",
    ownerId: "user_manager_chris",
    type: "estimate_rescue",
    status: "qualified",
    title: "Boiler replacement follow-up",
    description: "Proposal reopened after outreach response.",
    serviceType: "Boiler replacement",
    value: 9800,
    sourceLabel: "Comfort advisor",
    lastContactAt: isoDaysAgo(1),
    nextActionAt: isoDaysFromNow(2),
    createdAt: isoDaysAgo(12),
    updatedAt: isoDaysAgo(1),
  },
  {
    id: "opp_est_03",
    businessId: demoBusiness.id,
    contactId: "contact_16",
    locationId: "loc_main",
    ownerId: "user_manager_chris",
    type: "estimate_rescue",
    status: "booked",
    title: "Panel upgrade estimate recovered",
    description: "Customer booked after two-step estimate rescue sequence.",
    serviceType: "Electrical panel upgrade",
    value: 4100,
    sourceLabel: "Field quote",
    lastContactAt: isoDaysAgo(1),
    bookedAt: isoDaysFromNow(3, 13, 0),
    createdAt: isoDaysAgo(14),
    updatedAt: isoDaysAgo(1),
  },
  {
    id: "opp_est_04",
    businessId: demoBusiness.id,
    contactId: "contact_22",
    locationId: "loc_ann_arbor",
    ownerId: "user_manager_chris",
    type: "estimate_rescue",
    status: "paused",
    title: "Generator install financing follow-up",
    description: "Paused while homeowner reviews financing options.",
    serviceType: "Generator install",
    value: 11200,
    sourceLabel: "Sales rep",
    nextActionAt: isoDaysFromNow(5),
    createdAt: isoDaysAgo(11),
    updatedAt: isoDaysAgo(2),
  },
  {
    id: "opp_react_01",
    businessId: demoBusiness.id,
    contactId: "contact_03",
    locationId: "loc_main",
    ownerId: "user_manager_chris",
    campaignId: "camp_react_01",
    type: "reactivation",
    status: "qualified",
    title: "Dormant customer tune-up reactivation",
    description: "Customer replied to dormant win-back text and requested available dates.",
    serviceType: "AC tune-up",
    value: 289,
    sourceLabel: "Dormant segment",
    lastContactAt: isoDaysAgo(1),
    nextActionAt: isoDaysFromNow(2),
    createdAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(1),
  },
  {
    id: "opp_react_02",
    businessId: demoBusiness.id,
    contactId: "contact_09",
    locationId: "loc_ann_arbor",
    ownerId: "user_manager_chris",
    campaignId: "camp_react_01",
    type: "reactivation",
    status: "booked",
    title: "Replacement cycle candidate recovered",
    description: "Eight-year-old system owner booked estimate visit after reactivation email.",
    serviceType: "System replacement consultation",
    value: 12800,
    sourceLabel: "Replacement cycle",
    bookedAt: isoDaysFromNow(4),
    lastContactAt: isoDaysAgo(2),
    createdAt: isoDaysAgo(9),
    updatedAt: isoDaysAgo(2),
  },
  {
    id: "opp_react_03",
    businessId: demoBusiness.id,
    contactId: "contact_13",
    locationId: "loc_main",
    ownerId: "user_manager_chris",
    campaignId: "camp_react_02",
    type: "reactivation",
    status: "attempted",
    title: "Membership renewal outreach",
    description: "Membership expired 11 months ago and outreach sequence just launched.",
    serviceType: "Membership renewal",
    value: 249,
    sourceLabel: "Membership lapse",
    nextActionAt: isoDaysFromNow(3),
    createdAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
  },
  {
    id: "opp_react_04",
    businessId: demoBusiness.id,
    contactId: "contact_21",
    locationId: "loc_ann_arbor",
    ownerId: "user_manager_chris",
    campaignId: "camp_react_03",
    type: "reactivation",
    status: "new",
    title: "No-service-in-12-months segment candidate",
    description: "Queued to receive spring plumbing safety inspection offer.",
    serviceType: "Plumbing inspection",
    value: 189,
    sourceLabel: "12+ months dormant",
    nextActionAt: isoDaysFromNow(1),
    createdAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(1),
  },
];

export const demoOpportunityNotes: DemoOpportunityNote[] = [
  {
    id: "note_01",
    opportunityId: "opp_missed_01",
    authorId: "user_csr_jamie",
    body: "Sent missed-call SMS within 3 minutes. Customer replied that they are available tomorrow afternoon.",
    createdAt: isoHoursAgo(5),
  },
  {
    id: "note_02",
    opportunityId: "opp_missed_02",
    authorId: "user_csr_jamie",
    body: "Called back and left voicemail. Queueing second SMS with emergency messaging template.",
    createdAt: isoHoursAgo(4),
  },
  {
    id: "note_03",
    opportunityId: "opp_est_02",
    authorId: "user_manager_chris",
    body: "Homeowner wants to compare financing options on 84-month term.",
    createdAt: isoDaysAgo(1),
  },
  {
    id: "note_04",
    opportunityId: "opp_react_02",
    authorId: "user_manager_chris",
    body: "Replacement consult booked with comfort advisor after email click + reply.",
    createdAt: isoDaysAgo(2),
  },
  {
    id: "note_05",
    opportunityId: "opp_est_03",
    authorId: "user_manager_chris",
    body: "Recovered by estimate rescue campaign step 2 after no response to initial check-in.",
    createdAt: isoDaysAgo(1),
  },
];

export const demoCallEvents: DemoCallEvent[] = [
  {
    id: "call_01",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    contactId: "contact_11",
    locationId: "loc_ann_arbor",
    phoneNumber: "(734) 555-1011",
    direction: "inbound",
    classification: "missed",
    ringDurationSeconds: 42,
    isAfterHours: false,
    wasAnswered: false,
    wasBooked: true,
    summary: "Missed during lunch overflow; booked from follow-up SMS.",
    startedAt: isoHoursAgo(6),
    endedAt: isoHoursAgo(6),
  },
  {
    id: "call_02",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_02",
    contactId: "contact_15",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1015",
    direction: "inbound",
    classification: "after-hours",
    ringDurationSeconds: 51,
    isAfterHours: true,
    wasAnswered: false,
    wasBooked: false,
    summary: "Emergency no-heat voicemail received after hours.",
    startedAt: isoHoursAgo(10),
    endedAt: isoHoursAgo(10),
  },
  {
    id: "call_03",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_03",
    contactId: "contact_02",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1002",
    direction: "inbound",
    classification: "abandoned",
    ringDurationSeconds: 48,
    isAfterHours: false,
    wasAnswered: false,
    wasBooked: false,
    summary: "Caller hung up before CSR could answer.",
    startedAt: isoDaysAgo(3, 16, 20),
    endedAt: isoDaysAgo(3, 16, 21),
  },
  {
    id: "call_04",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_04",
    contactId: "contact_20",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1020",
    direction: "inbound",
    classification: "responded",
    ringDurationSeconds: 33,
    isAfterHours: false,
    wasAnswered: false,
    wasBooked: false,
    summary: "Callback text sent, customer replied with preferred install window.",
    startedAt: isoHoursAgo(8),
    endedAt: isoHoursAgo(8),
  },
  {
    id: "call_05",
    businessId: demoBusiness.id,
    contactId: "contact_01",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1001",
    direction: "inbound",
    classification: "booked",
    ringDurationSeconds: 18,
    isAfterHours: false,
    wasAnswered: true,
    wasBooked: true,
    summary: "CSR answered and converted into spring tune-up booking.",
    startedAt: isoDaysAgo(1, 14, 5),
    endedAt: isoDaysAgo(1, 14, 7),
  },
  {
    id: "call_06",
    businessId: demoBusiness.id,
    contactId: "contact_10",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1010",
    direction: "inbound",
    classification: "lost",
    ringDurationSeconds: 55,
    isAfterHours: false,
    wasAnswered: false,
    wasBooked: false,
    summary: "Competitor already booked when callback was attempted.",
    startedAt: isoDaysAgo(4, 12, 10),
    endedAt: isoDaysAgo(4, 12, 11),
  },
  {
    id: "call_07",
    businessId: demoBusiness.id,
    contactId: "contact_18",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1018",
    direction: "inbound",
    classification: "responded",
    ringDurationSeconds: 25,
    isAfterHours: false,
    wasAnswered: true,
    wasBooked: false,
    summary: "Drain issue triaged and estimate visit scheduled for tomorrow.",
    startedAt: isoDaysAgo(2, 10, 30),
    endedAt: isoDaysAgo(2, 10, 32),
  },
  {
    id: "call_08",
    businessId: demoBusiness.id,
    contactId: "contact_14",
    locationId: "loc_main",
    phoneNumber: "(248) 555-1014",
    direction: "inbound",
    classification: "missed",
    ringDurationSeconds: 37,
    isAfterHours: false,
    wasAnswered: false,
    wasBooked: false,
    summary: "Boiler issue call missed during dispatch peak.",
    startedAt: isoDaysAgo(1, 17, 40),
    endedAt: isoDaysAgo(1, 17, 41),
  },
];

export const demoEstimates: DemoEstimate[] = [
  {
    id: "est_01",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_01",
    contactId: "contact_05",
    locationId: "loc_ann_arbor",
    estimateNumber: "EST-1041",
    serviceType: "Mini-split install",
    amount: 6400,
    status: "stale",
    sentAt: isoDaysAgo(8),
    staleAt: isoDaysAgo(1),
  },
  {
    id: "est_02",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_02",
    contactId: "contact_08",
    locationId: "loc_main",
    estimateNumber: "EST-1042",
    serviceType: "Boiler replacement",
    amount: 9800,
    status: "responded",
    sentAt: isoDaysAgo(12),
    staleAt: isoDaysAgo(5),
    respondedAt: isoDaysAgo(1),
  },
  {
    id: "est_03",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_03",
    contactId: "contact_16",
    locationId: "loc_main",
    estimateNumber: "EST-1043",
    serviceType: "Electrical panel upgrade",
    amount: 4100,
    status: "booked",
    sentAt: isoDaysAgo(14),
    staleAt: isoDaysAgo(7),
    bookedAt: isoDaysAgo(1),
  },
  {
    id: "est_04",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_04",
    contactId: "contact_22",
    locationId: "loc_ann_arbor",
    estimateNumber: "EST-1044",
    serviceType: "Generator install",
    amount: 11200,
    status: "open",
    sentAt: isoDaysAgo(4),
  },
  {
    id: "est_05",
    businessId: demoBusiness.id,
    contactId: "contact_14",
    locationId: "loc_main",
    estimateNumber: "EST-1045",
    serviceType: "Boiler tune-up",
    amount: 390,
    status: "open",
    sentAt: isoDaysAgo(2),
  },
  {
    id: "est_06",
    businessId: demoBusiness.id,
    contactId: "contact_10",
    locationId: "loc_main",
    estimateNumber: "EST-1046",
    serviceType: "Water heater install",
    amount: 3200,
    status: "lost",
    sentAt: isoDaysAgo(16),
    staleAt: isoDaysAgo(9),
    lostAt: isoDaysAgo(2),
  },
  {
    id: "est_07",
    businessId: demoBusiness.id,
    contactId: "contact_18",
    locationId: "loc_main",
    estimateNumber: "EST-1047",
    serviceType: "Drain line replacement",
    amount: 2100,
    status: "stale",
    sentAt: isoDaysAgo(9),
    staleAt: isoDaysAgo(2),
  },
  {
    id: "est_08",
    businessId: demoBusiness.id,
    contactId: "contact_12",
    locationId: "loc_ann_arbor",
    estimateNumber: "EST-1048",
    serviceType: "Whole-home surge protection",
    amount: 780,
    status: "open",
    sentAt: isoDaysAgo(3),
  },
];

export const demoCampaigns: DemoCampaign[] = [
  {
    id: "camp_missed_01",
    businessId: demoBusiness.id,
    name: "Missed Call Recovery - Standard",
    type: "missed_call_followup",
    status: "active",
    segmentName: "All missed inbound calls",
    channel: "sms",
    goal: "Recover missed calls within 14 minutes",
    launchedAt: isoDaysAgo(21),
  },
  {
    id: "camp_react_01",
    businessId: demoBusiness.id,
    name: "Dormant Customer Tune-Up Push",
    type: "reactivation",
    status: "active",
    segmentName: "No service in 12+ months",
    channel: "email",
    goal: "Book spring tune-up visits",
    launchedAt: isoDaysAgo(9),
  },
  {
    id: "camp_react_02",
    businessId: demoBusiness.id,
    name: "Membership Renewal Win-Back",
    type: "reactivation",
    status: "draft",
    segmentName: "Membership renewal",
    channel: "sms",
    goal: "Recover expired memberships",
  },
  {
    id: "camp_react_03",
    businessId: demoBusiness.id,
    name: "Replacement Cycle Outreach",
    type: "reactivation",
    status: "scheduled",
    segmentName: "Replacement cycle candidates",
    channel: "email",
    goal: "Generate high-ticket consultation demand",
    launchedAt: isoDaysFromNow(1),
  },
];

export const demoTemplates: DemoTemplate[] = [
  {
    id: "tpl_sms_missed",
    businessId: demoBusiness.id,
    name: "Missed Call - Fast Apology",
    category: "missed_call",
    channel: "sms",
    body: "Hi {{firstName}}, sorry we missed your call to North Shore. Want to text us the issue and best time for a callback?",
    variables: ["firstName"],
    isArchived: false,
  },
  {
    id: "tpl_sms_estimate",
    businessId: demoBusiness.id,
    name: "Estimate Rescue - Friendly Check-In",
    category: "estimate_rescue",
    channel: "sms",
    body: "Hi {{firstName}}, just checking in on your {{serviceType}} proposal. Want us to answer any questions or review options?",
    variables: ["firstName", "serviceType"],
    isArchived: false,
  },
  {
    id: "tpl_email_reactivation",
    businessId: demoBusiness.id,
    name: "Dormant Reactivation - Seasonal Offer",
    category: "reactivation",
    channel: "email",
    subject: "Spring service reminder from North Shore",
    body: "We noticed it has been a while since your last visit. This month we are opening extra tune-up slots for returning customers.",
    variables: ["firstName"],
    isArchived: false,
  },
  {
    id: "tpl_sms_membership",
    businessId: demoBusiness.id,
    name: "Membership Renewal Reminder",
    category: "reactivation",
    channel: "sms",
    body: "Your North Shore membership benefits are ready to renew. Reply RENEW for options and priority scheduling.",
    variables: [],
    isArchived: false,
  },
];

export const demoCampaignSteps: DemoCampaignStep[] = [
  {
    id: "step_01",
    campaignId: "camp_missed_01",
    templateId: "tpl_sms_missed",
    position: 1,
    title: "Immediate missed-call apology",
    channel: "sms",
    delayHours: 0,
    stopOnReply: true,
    stopOnBooking: true,
  },
  {
    id: "step_02",
    campaignId: "camp_missed_01",
    position: 2,
    title: "CSR callback reminder",
    channel: "sms",
    delayHours: 2,
    stopOnReply: true,
    stopOnBooking: true,
    bodyOverride: "Still need help with your home service issue? Reply here and we can get you scheduled.",
  },
  {
    id: "step_03",
    campaignId: "camp_react_01",
    templateId: "tpl_email_reactivation",
    position: 1,
    title: "Seasonal email outreach",
    channel: "email",
    delayHours: 0,
    stopOnReply: false,
    stopOnBooking: false,
  },
  {
    id: "step_04",
    campaignId: "camp_react_01",
    templateId: "tpl_sms_membership",
    position: 2,
    title: "SMS reminder for openers",
    channel: "sms",
    delayHours: 72,
    stopOnReply: true,
    stopOnBooking: true,
  },
  {
    id: "step_05",
    campaignId: "camp_react_02",
    templateId: "tpl_sms_membership",
    position: 1,
    title: "Membership expiration reminder",
    channel: "sms",
    delayHours: 0,
    stopOnReply: true,
    stopOnBooking: true,
  },
  {
    id: "step_06",
    campaignId: "camp_react_03",
    templateId: "tpl_email_reactivation",
    position: 1,
    title: "Replacement cycle consultation intro",
    channel: "email",
    delayHours: 0,
    stopOnReply: true,
    stopOnBooking: true,
  },
];

export const demoMessageEvents: DemoMessageEvent[] = [
  {
    id: "msg_01",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    contactId: "contact_11",
    campaignId: "camp_missed_01",
    templateId: "tpl_sms_missed",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    body: "Hi Amy, sorry we missed your call to North Shore. Want to text us the issue and best time for a callback?",
    sentAt: isoHoursAgo(5.8),
    deliveredAt: isoHoursAgo(5.7),
    createdAt: isoHoursAgo(5.8),
  },
  {
    id: "msg_02",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    contactId: "contact_11",
    channel: "sms",
    direction: "inbound",
    status: "replied",
    body: "AC is blowing warm air. Tomorrow after 2 works for me.",
    repliedAt: isoHoursAgo(5.4),
    createdAt: isoHoursAgo(5.4),
  },
  {
    id: "msg_03",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_02",
    contactId: "contact_15",
    campaignId: "camp_missed_01",
    templateId: "tpl_sms_missed",
    channel: "sms",
    direction: "outbound",
    status: "sent",
    body: "Hi Aisha, sorry we missed your call. Reply with the issue and we can coordinate the fastest callback.",
    sentAt: isoHoursAgo(4.8),
    createdAt: isoHoursAgo(4.8),
  },
  {
    id: "msg_04",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_04",
    contactId: "contact_20",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    body: "Thanks for calling North Shore. We can review water heater options by text if that's easier.",
    sentAt: isoHoursAgo(3.5),
    deliveredAt: isoHoursAgo(3.4),
    createdAt: isoHoursAgo(3.5),
  },
  {
    id: "msg_05",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_04",
    contactId: "contact_20",
    channel: "sms",
    direction: "inbound",
    status: "replied",
    body: "Yes, can someone text me install options for a 50-gallon gas tank?",
    repliedAt: isoHoursAgo(3),
    createdAt: isoHoursAgo(3),
  },
  {
    id: "msg_06",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_02",
    contactId: "contact_08",
    templateId: "tpl_sms_estimate",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    body: "Hi Tyler, just checking in on your boiler replacement proposal. Want us to review financing options?",
    sentAt: isoDaysAgo(2),
    deliveredAt: isoDaysAgo(2),
    createdAt: isoDaysAgo(2),
  },
  {
    id: "msg_07",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_02",
    contactId: "contact_08",
    channel: "sms",
    direction: "inbound",
    status: "replied",
    body: "Yes, can someone call me about monthly payment options?",
    repliedAt: isoDaysAgo(1),
    createdAt: isoDaysAgo(1),
  },
  {
    id: "msg_08",
    businessId: demoBusiness.id,
    opportunityId: "opp_react_02",
    contactId: "contact_09",
    campaignId: "camp_react_01",
    templateId: "tpl_email_reactivation",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    body: "We noticed it has been a while since your last visit. Book a replacement consultation this week.",
    sentAt: isoDaysAgo(4),
    deliveredAt: isoDaysAgo(4),
    createdAt: isoDaysAgo(4),
  },
  {
    id: "msg_09",
    businessId: demoBusiness.id,
    opportunityId: "opp_react_02",
    contactId: "contact_09",
    channel: "email",
    direction: "inbound",
    status: "replied",
    body: "I'd like to review replacement options next week.",
    repliedAt: isoDaysAgo(3),
    createdAt: isoDaysAgo(3),
  },
];

export const demoBookings: DemoBooking[] = [
  {
    id: "booking_01",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    contactId: "contact_11",
    locationId: "loc_ann_arbor",
    sourceType: "missed_call",
    attributionMethod: "direct",
    title: "AC diagnostic appointment",
    scheduledFor: isoDaysFromNow(1, 15, 0),
    revenue: 780,
    notes: "Booked from SMS reply recovery.",
  },
  {
    id: "booking_02",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_03",
    contactId: "contact_16",
    locationId: "loc_main",
    sourceType: "estimate_rescue",
    attributionMethod: "direct",
    title: "Electrical panel upgrade install",
    scheduledFor: isoDaysFromNow(3, 13, 0),
    revenue: 4100,
  },
  {
    id: "booking_03",
    businessId: demoBusiness.id,
    opportunityId: "opp_react_02",
    contactId: "contact_09",
    locationId: "loc_ann_arbor",
    sourceType: "reactivation",
    attributionMethod: "influenced",
    title: "Replacement consultation",
    scheduledFor: isoDaysFromNow(4, 10, 0),
    revenue: 12800,
  },
  {
    id: "booking_04",
    businessId: demoBusiness.id,
    contactId: "contact_01",
    locationId: "loc_main",
    sourceType: "manual",
    attributionMethod: "direct",
    title: "Spring tune-up",
    scheduledFor: isoDaysFromNow(2, 11, 0),
    revenue: 189,
  },
  {
    id: "booking_05",
    businessId: demoBusiness.id,
    contactId: "contact_03",
    locationId: "loc_main",
    sourceType: "reactivation",
    attributionMethod: "influenced",
    title: "Tune-up reactivation visit",
    scheduledFor: isoDaysFromNow(5, 9, 0),
    revenue: 289,
  },
  {
    id: "booking_06",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_04",
    contactId: "contact_20",
    locationId: "loc_main",
    sourceType: "missed_call",
    attributionMethod: "influenced",
    title: "Water heater estimate visit",
    scheduledFor: isoDaysFromNow(2, 16, 0),
    revenue: 3200,
  },
];

export const demoActivityLogs: DemoActivityLog[] = [
  {
    id: "activity_01",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    actorUserId: "user_csr_jamie",
    type: "workflow",
    title: "Missed call auto-text sent",
    message: "Auto-response SMS sent 3 minutes after missed inbound call.",
    createdAt: isoHoursAgo(5.8),
  },
  {
    id: "activity_02",
    businessId: demoBusiness.id,
    opportunityId: "opp_missed_01",
    contactId: "contact_11",
    type: "reply",
    title: "Customer replied",
    message: "Amy replied with issue details and preferred booking window.",
    createdAt: isoHoursAgo(5.4),
  },
  {
    id: "activity_03",
    businessId: demoBusiness.id,
    opportunityId: "opp_est_03",
    actorUserId: "user_manager_chris",
    type: "estimate",
    title: "Estimate rescue converted",
    message: "Panel upgrade estimate moved from stale to booked.",
    createdAt: isoDaysAgo(1),
  },
  {
    id: "activity_04",
    businessId: demoBusiness.id,
    opportunityId: "opp_react_02",
    campaignId: "camp_react_01",
    type: "campaign",
    title: "Reactivation campaign influenced booking",
    message: "Replacement-cycle contact booked consultation from campaign sequence.",
    createdAt: isoDaysAgo(2),
  },
  {
    id: "activity_05",
    businessId: demoBusiness.id,
    type: "alert",
    title: "High-value stale estimate",
    message: "Generator install estimate over $10k needs manager review.",
    createdAt: isoDaysAgo(1),
  },
  {
    id: "activity_06",
    businessId: demoBusiness.id,
    type: "alert",
    title: "After-hours missed call",
    message: "Emergency no-heat call still waiting on second-touch follow-up.",
    createdAt: isoHoursAgo(4),
  },
  {
    id: "activity_07",
    businessId: demoBusiness.id,
    campaignId: "camp_react_03",
    type: "campaign",
    title: "Replacement cycle campaign scheduled",
    message: "Campaign queued for tomorrow morning launch.",
    createdAt: isoHoursAgo(7),
  },
];

export const demoIntegrationConnections: DemoIntegrationConnection[] = [
  {
    id: "int_01",
    businessId: demoBusiness.id,
    provider: "twilio",
    status: "connected",
    externalAccountId: "AC123-DEMO",
    lastSyncAt: isoHoursAgo(1),
  },
  {
    id: "int_02",
    businessId: demoBusiness.id,
    provider: "jobber",
    status: "pending",
    lastSyncAt: isoDaysAgo(1),
  },
  {
    id: "int_03",
    businessId: demoBusiness.id,
    provider: "housecall_pro",
    status: "disconnected",
  },
  {
    id: "int_04",
    businessId: demoBusiness.id,
    provider: "servicetitan",
    status: "error",
    lastSyncAt: isoDaysAgo(2),
    errorMessage: "Token expired during sync.",
  },
  {
    id: "int_05",
    businessId: demoBusiness.id,
    provider: "gmail",
    status: "connected",
    lastSyncAt: isoHoursAgo(6),
  },
  {
    id: "int_06",
    businessId: demoBusiness.id,
    provider: "outlook",
    status: "disconnected",
  },
  {
    id: "int_07",
    businessId: demoBusiness.id,
    provider: "google_calendar",
    status: "connected",
    lastSyncAt: isoHoursAgo(2),
  },
  {
    id: "int_08",
    businessId: demoBusiness.id,
    provider: "csv",
    status: "connected",
    lastSyncAt: isoDaysAgo(5),
  },
];

export const demoReportSnapshots: DemoReportSnapshot[] = [
  {
    id: "report_30d",
    businessId: demoBusiness.id,
    label: "Last 30 days",
    periodStart: isoDaysAgo(30),
    periodEnd: now.toISOString(),
    revenueDirect: 4880,
    revenueInfluenced: 16289,
    opportunitiesRecovered: 14,
    bookingsCreated: 8,
    avgResponseMinutes: 11,
    estimatesReopened: 5,
    customersReactivated: 4,
    workflowBreakdown: [
      { type: "missed_call", recoveredRevenue: 3980, bookings: 3, conversionRate: 46 },
      { type: "estimate_rescue", recoveredRevenue: 4100, bookings: 2, conversionRate: 31 },
      { type: "reactivation", recoveredRevenue: 13089, bookings: 3, conversionRate: 24 },
    ],
    trend: [
      { date: "Mar 01", direct: 280, influenced: 450, opportunities: 2 },
      { date: "Mar 05", direct: 620, influenced: 1100, opportunities: 3 },
      { date: "Mar 09", direct: 400, influenced: 1700, opportunities: 3 },
      { date: "Mar 12", direct: 950, influenced: 2400, opportunities: 4 },
      { date: "Mar 15", direct: 1230, influenced: 3200, opportunities: 4 },
      { date: "Mar 18", direct: 1400, influenced: 7439, opportunities: 5 },
    ],
  },
  {
    id: "report_7d",
    businessId: demoBusiness.id,
    label: "Last 7 days",
    periodStart: isoDaysAgo(7),
    periodEnd: now.toISOString(),
    revenueDirect: 780,
    revenueInfluenced: 16089,
    opportunitiesRecovered: 6,
    bookingsCreated: 4,
    avgResponseMinutes: 9,
    estimatesReopened: 3,
    customersReactivated: 2,
    workflowBreakdown: [
      { type: "missed_call", recoveredRevenue: 3980, bookings: 2, conversionRate: 50 },
      { type: "estimate_rescue", recoveredRevenue: 4100, bookings: 1, conversionRate: 33 },
      { type: "reactivation", recoveredRevenue: 8789, bookings: 1, conversionRate: 20 },
    ],
    trend: [
      { date: "Mar 12", direct: 120, influenced: 500, opportunities: 1 },
      { date: "Mar 13", direct: 200, influenced: 900, opportunities: 2 },
      { date: "Mar 14", direct: 0, influenced: 1200, opportunities: 1 },
      { date: "Mar 15", direct: 0, influenced: 3200, opportunities: 1 },
      { date: "Mar 16", direct: 0, influenced: 4100, opportunities: 1 },
      { date: "Mar 17", direct: 0, influenced: 12800, opportunities: 1 },
      { date: "Mar 18", direct: 780, influenced: 16089, opportunities: 2 },
    ],
  },
];

export const demoAlerts: DemoAlert[] = [
  {
    id: "alert_01",
    severity: "high",
    title: "1 emergency missed call needs follow-up",
    message: "After-hours furnace lead is still open and SLA is approaching 15 minutes.",
    actionLabel: "Open calls queue",
    href: "/app/calls",
  },
  {
    id: "alert_02",
    severity: "medium",
    title: "2 stale estimates crossed high-value threshold",
    message: "Generator and boiler proposals need manager review before the end of the day.",
    actionLabel: "Review estimates",
    href: "/app/estimates",
  },
  {
    id: "alert_03",
    severity: "low",
    title: "Replacement campaign is scheduled for tomorrow",
    message: "Confirm copy and stop conditions before launch.",
    actionLabel: "Inspect campaign",
    href: "/app/campaigns",
  },
];

export function buildDemoTenantData(): DemoTenantData {
  return {
    business: { ...demoBusiness },
    users: demoUsers.map((item) => ({ ...item })),
    locations: demoLocations.map((item) => ({ ...item })),
    contacts: demoContacts.map((item) => ({ ...item, tags: [...item.tags] })),
    opportunities: demoOpportunities.map((item) => ({ ...item })),
    opportunityNotes: demoOpportunityNotes.map((item) => ({ ...item })),
    callEvents: demoCallEvents.map((item) => ({ ...item })),
    estimates: demoEstimates.map((item) => ({ ...item })),
    campaigns: demoCampaigns.map((item) => ({ ...item })),
    campaignSteps: demoCampaignSteps.map((item) => ({ ...item })),
    templates: demoTemplates.map((item) => ({ ...item, variables: [...item.variables] })),
    messageEvents: demoMessageEvents.map((item) => ({ ...item })),
    bookings: demoBookings.map((item) => ({ ...item })),
    activityLogs: demoActivityLogs.map((item) => ({
      ...item,
      metadata: item.metadata ? { ...item.metadata } : undefined,
    })),
    integrationConnections: demoIntegrationConnections.map((item) => ({
      ...item,
      config: item.config ? { ...item.config } : undefined,
    })),
    reportSnapshots: demoReportSnapshots.map((item) => ({
      ...item,
      workflowBreakdown: item.workflowBreakdown.map((entry) => ({ ...entry })),
      trend: item.trend.map((entry) => ({ ...entry })),
    })),
    alerts: demoAlerts.map((item) => ({ ...item })),
  };
}
