import { subDays, subHours } from "date-fns";

export const DEMO_OPPORTUNITIES = [
  {
    id: "opp-1",
    type: "missed_call",
    status: "booked",
    title: "Missed Call — Robert Caldwell",
    serviceType: "AC Tune-Up",
    estimatedValue: 189,
    actualValue: 189,
    followUpCount: 2,
    createdAt: subDays(new Date(), 5),
    lastContactAt: subDays(new Date(), 4),
    resolvedAt: subDays(new Date(), 4),
    contact: { id: "c1", firstName: "Robert", lastName: "Caldwell", phone: "(734) 555-1001", email: "r.caldwell@email.com", type: "customer", status: "active" },
    assignedTo: { id: "u2", name: "James Rivera", email: "csr@northshoreht.com" },
    _count: { notes: 1, callEvents: 1, messageEvents: 2, bookings: 1 },
  },
  {
    id: "opp-2",
    type: "missed_call",
    status: "responded",
    title: "Missed Call — David Kim",
    serviceType: "HVAC Repair",
    estimatedValue: 450,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 2),
    lastContactAt: subDays(new Date(), 2),
    resolvedAt: null,
    contact: { id: "c5", firstName: "David", lastName: "Kim", phone: "(248) 555-1005", email: "dkim@email.com", type: "lead", status: "active" },
    assignedTo: { id: "u2", name: "James Rivera", email: "csr@northshoreht.com" },
    _count: { notes: 1, callEvents: 1, messageEvents: 2, bookings: 0 },
  },
  {
    id: "opp-3",
    type: "missed_call",
    status: "new",
    title: "Missed Call — Chris Delgado",
    serviceType: null,
    estimatedValue: 0,
    actualValue: null,
    followUpCount: 0,
    createdAt: subHours(new Date(), 3),
    lastContactAt: null,
    resolvedAt: null,
    contact: { id: "c9", firstName: "Chris", lastName: "Delgado", phone: "(734) 555-1009", email: "c.delgado@email.com", type: "lead", status: "active" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 1, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-4",
    type: "missed_call",
    status: "attempted",
    title: "Missed Call — Gary Larson",
    serviceType: "Plumbing Repair",
    estimatedValue: 320,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 1),
    lastContactAt: subDays(new Date(), 1),
    resolvedAt: null,
    contact: { id: "c15", firstName: "Gary", lastName: "Larson", phone: "(586) 555-1015", email: "g.larson@email.com", type: "lead", status: "active" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 1, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-5",
    type: "estimate_rescue",
    status: "booked",
    title: "Estimate Follow-Up — Furnace Replacement",
    serviceType: "Furnace Repair",
    estimatedValue: 4800,
    actualValue: 4800,
    followUpCount: 2,
    createdAt: subDays(new Date(), 12),
    lastContactAt: subDays(new Date(), 11),
    resolvedAt: subDays(new Date(), 11),
    contact: { id: "c2", firstName: "Linda", lastName: "Morrison", phone: "(734) 555-1002", email: "linda.m@email.com", type: "customer", status: "dormant" },
    assignedTo: { id: "u1", name: "Sarah Chen", email: "manager@northshoreht.com" },
    _count: { notes: 2, callEvents: 0, messageEvents: 2, bookings: 1 },
  },
  {
    id: "opp-6",
    type: "estimate_rescue",
    status: "responded",
    title: "Estimate Follow-Up — Water Heater Install",
    serviceType: "Water Heater",
    estimatedValue: 1650,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 8),
    lastContactAt: subDays(new Date(), 7),
    resolvedAt: null,
    contact: { id: "c7", firstName: "Kevin", lastName: "Stern", phone: "(248) 555-1007", email: "kstern@email.com", type: "customer", status: "active" },
    assignedTo: { id: "u1", name: "Sarah Chen", email: "manager@northshoreht.com" },
    _count: { notes: 1, callEvents: 0, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-7",
    type: "estimate_rescue",
    status: "new",
    title: "Estimate Follow-Up — 200A Panel Upgrade",
    serviceType: "Panel Upgrade",
    estimatedValue: 3200,
    actualValue: null,
    followUpCount: 0,
    createdAt: subDays(new Date(), 14),
    lastContactAt: null,
    resolvedAt: null,
    contact: { id: "c13", firstName: "Paul", lastName: "Thornton", phone: "(248) 555-1013", email: "p.thornton@email.com", type: "customer", status: "dormant" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 0, bookings: 0 },
  },
  {
    id: "opp-8",
    type: "estimate_rescue",
    status: "new",
    title: "Estimate Follow-Up — 2.5-Ton AC Replacement",
    serviceType: "HVAC Installation",
    estimatedValue: 6400,
    actualValue: null,
    followUpCount: 0,
    createdAt: subDays(new Date(), 9),
    lastContactAt: null,
    resolvedAt: null,
    contact: { id: "c21", firstName: "Eric", lastName: "Zimmerman", phone: "(248) 555-1021", email: "e.zimmerman@email.com", type: "customer", status: "active" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 0, bookings: 0 },
  },
  {
    id: "opp-9",
    type: "reactivation",
    status: "booked",
    title: "Reactivation — Linda Morrison",
    serviceType: "HVAC Repair",
    estimatedValue: 2800,
    actualValue: 2800,
    followUpCount: 2,
    createdAt: subDays(new Date(), 18),
    lastContactAt: subDays(new Date(), 17),
    resolvedAt: subDays(new Date(), 17),
    contact: { id: "c2", firstName: "Linda", lastName: "Morrison", phone: "(734) 555-1002", email: "linda.m@email.com", type: "customer", status: "dormant" },
    assignedTo: { id: "u1", name: "Sarah Chen", email: "manager@northshoreht.com" },
    _count: { notes: 1, callEvents: 0, messageEvents: 2, bookings: 1 },
  },
  {
    id: "opp-10",
    type: "reactivation",
    status: "responded",
    title: "Reactivation — Nancy Ostrowski",
    serviceType: "Maintenance Plan",
    estimatedValue: 299,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 10),
    lastContactAt: subDays(new Date(), 9),
    resolvedAt: null,
    contact: { id: "c8", firstName: "Nancy", lastName: "Ostrowski", phone: "(586) 555-1008", email: "n.ostrowski@email.com", type: "customer", status: "dormant" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-11",
    type: "reactivation",
    status: "responded",
    title: "Reactivation — Tom Bancroft",
    serviceType: "AC Tune-Up",
    estimatedValue: 189,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 7),
    lastContactAt: subDays(new Date(), 6),
    resolvedAt: null,
    contact: { id: "c3", firstName: "Tom", lastName: "Bancroft", phone: "(313) 555-1003", email: "tbancroft@email.com", type: "customer", status: "dormant" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-12",
    type: "reactivation",
    status: "attempted",
    title: "Reactivation — Patricia Nguyen",
    serviceType: "Furnace Repair",
    estimatedValue: 850,
    actualValue: null,
    followUpCount: 1,
    createdAt: subDays(new Date(), 4),
    lastContactAt: subDays(new Date(), 4),
    resolvedAt: null,
    contact: { id: "c6", firstName: "Patricia", lastName: "Nguyen", phone: "(248) 555-1006", email: "p.nguyen@email.com", type: "customer", status: "dormant" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 1, bookings: 0 },
  },
  {
    id: "opp-13",
    type: "reactivation",
    status: "new",
    title: "Reactivation — Carol Vasquez",
    serviceType: "Plumbing Repair",
    estimatedValue: 420,
    actualValue: null,
    followUpCount: 0,
    createdAt: subDays(new Date(), 3),
    lastContactAt: null,
    resolvedAt: null,
    contact: { id: "c20", firstName: "Carol", lastName: "Vasquez", phone: "(313) 555-1020", email: "c.vasquez@email.com", type: "customer", status: "dormant" },
    assignedTo: null,
    _count: { notes: 0, callEvents: 0, messageEvents: 1, bookings: 0 },
  },
];
